# Generated by Django 5.2.15 on 2026-06-15 03:16

import django.db.models.deletion
import django.utils.timezone
import kb.models
from django.conf import settings
from django.db import migrations, models


AUDIT_TABLES = [
    "kb_authactivitylog",
    "kb_activitylog",
    "kb_articleimageuploadlog",
]

UPDATE_FUNCTION_SQL = r"""
CREATE OR REPLACE FUNCTION kb_block_audit_log_update()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'Audit log rows are append-only and cannot be updated.';
END;
$$ LANGUAGE plpgsql;
"""

DELETE_FUNCTION_SQL = r"""
CREATE OR REPLACE FUNCTION kb_block_audit_log_delete_unless_retention_cleanup()
RETURNS trigger AS $$
BEGIN
    IF COALESCE(current_setting('djopenkb.audit_retention_cleanup', true), '') = 'on' THEN
        RETURN OLD;
    END IF;

    RAISE EXCEPTION 'Audit log rows cannot be manually deleted. They are removed only by retention cleanup.';
END;
$$ LANGUAGE plpgsql;
"""

DEFAULT_AUTH_LOCKOUT_STAGES = [
    # sort_order, failure_limit, block_seconds, repeat_count
    (10, 10, 300, 2),   # 10 failures -> 5 minutes, twice
    (20, 5, 900, 2),    # 5 failures -> 15 minutes, twice
    (30, 3, 3600, 0),   # 3 failures -> 1 hour, repeat forever
]


def install_audit_log_triggers(apps, schema_editor):
    """Install PostgreSQL append-only triggers for audit tables.

    SQLite/dev installs skip this safely. PostgreSQL production installs block
    normal UPDATE/DELETE on audit logs, while retention cleanup can delete old
    rows only when it sets the djopenkb.audit_retention_cleanup session flag.
    """
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(UPDATE_FUNCTION_SQL)
        cursor.execute(DELETE_FUNCTION_SQL)

        for table in AUDIT_TABLES:
            update_trigger = f"{table}_block_update"
            delete_trigger = f"{table}_block_delete"
            cursor.execute(f'DROP TRIGGER IF EXISTS {update_trigger} ON "{table}";')
            cursor.execute(f'DROP TRIGGER IF EXISTS {delete_trigger} ON "{table}";')
            cursor.execute(
                f"""
                CREATE TRIGGER {update_trigger}
                BEFORE UPDATE ON "{table}"
                FOR EACH ROW
                EXECUTE FUNCTION kb_block_audit_log_update();
                """
            )
            cursor.execute(
                f"""
                CREATE TRIGGER {delete_trigger}
                BEFORE DELETE ON "{table}"
                FOR EACH ROW
                EXECUTE FUNCTION kb_block_audit_log_delete_unless_retention_cleanup();
                """
            )


def remove_audit_log_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        for table in AUDIT_TABLES:
            update_trigger = f"{table}_block_update"
            delete_trigger = f"{table}_block_delete"
            cursor.execute(f'DROP TRIGGER IF EXISTS {update_trigger} ON "{table}";')
            cursor.execute(f'DROP TRIGGER IF EXISTS {delete_trigger} ON "{table}";')

        cursor.execute("DROP FUNCTION IF EXISTS kb_block_audit_log_update();")
        cursor.execute("DROP FUNCTION IF EXISTS kb_block_audit_log_delete_unless_retention_cleanup();")


def create_default_site_settings(apps, schema_editor):
    SiteSetting = apps.get_model("kb", "SiteSetting")
    AuthLockoutPolicyStage = apps.get_model("kb", "AuthLockoutPolicyStage")

    setting, _created = SiteSetting.objects.get_or_create(pk=1)
    if not AuthLockoutPolicyStage.objects.filter(site_setting=setting).exists():
        AuthLockoutPolicyStage.objects.bulk_create(
            [
                AuthLockoutPolicyStage(
                    site_setting=setting,
                    sort_order=sort_order,
                    failure_limit=failure_limit,
                    block_seconds=block_seconds,
                    repeat_count=repeat_count,
                    enabled=True,
                )
                for sort_order, failure_limit, block_seconds, repeat_count in DEFAULT_AUTH_LOCKOUT_STAGES
            ]
        )


def remove_default_site_settings(apps, schema_editor):
    # Keep settings on rollback to avoid unexpectedly deleting admin-edited policy.
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stray_upload_cleanup_min_age_minutes', models.PositiveIntegerField(default=1440, help_text='Files newer than this many minutes are ignored by the stray upload cleanup tool. Default is 1440 minutes (24 hours) to avoid deleting images while users are drafting articles. Set to 0 to detect/delete stray uploads immediately.', verbose_name='Stray upload cleanup minimum age (minutes)')),
                ('article_image_upload_limit', models.PositiveIntegerField(default=50, help_text='Maximum number of pasted/uploaded images allowed per article, including draft, pending, published, and pending-update versions. Default is 50. Set to 0 to disable article image uploads.', verbose_name='Article image upload limit')),
                ('articles_per_page', models.PositiveIntegerField(default=10, help_text='Number of published articles shown per page in search/results and in each homepage article column such as Trending Topics, Most Liked, and Most Recent Articles. Recommended range: 5 to 100. Default is 10.', verbose_name='Articles per page')),
                ('auth_activity_log_retention_days', models.PositiveIntegerField(default=30, help_text='Authentication/MFA monitoring logs older than this many days can be deleted by the cleanup command. Use 0 to keep authentication activity logs indefinitely.', verbose_name='Authentication activity log retention (days)')),
                ('session_timeout_days', models.PositiveIntegerField(default=30, help_text='Authenticated user sessions expire after this many days from sign-in. After expiry, users are signed out and must log in again. Set to 0 to expire the session when the browser closes.', verbose_name='User session timeout (days)')),
                ('activity_log_retention_days', models.PositiveIntegerField(default=30, help_text='Article/vote/image/admin-tool activity logs older than this many days can be deleted by the cleanup command. Use 0 to keep general activity logs indefinitely.', verbose_name='General activity log retention (days)')),
                ('admin_log_rows_per_page', models.PositiveIntegerField(default=200, help_text='Number of rows to show per page in Django Admin log tables. Recommended range: 50 to 500. Default is 200.', verbose_name='Admin log rows per page')),
                ('admin_allowed_cidrs', models.TextField(default='10.65.0.0/16,127.0.0.1/32,::1/128', help_text='Comma or newline separated CIDR/IP allowlist for Django Admin access. Default allows 10.65.0.0/16 and local loopback. Users outside this range receive 404 even if they know the admin URL. Nginx may also enforce a separate outer allowlist in nginx/nginx.conf.', verbose_name='Admin allowed IP ranges')),
                ('auth_lockout_strike_ttl_seconds', models.PositiveIntegerField(default=604800, help_text='How long failed-login/MFA escalation history is remembered without a successful login. Successful verification clears it immediately. Default is 604800 seconds (7 days).', verbose_name='Authentication lockout escalation memory (seconds)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site setting',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='AuthLockoutPolicyStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=10, help_text='Lower numbers run first. Use 10, 20, 30, etc. so you can insert stages later.', verbose_name='Stage order')),
                ('failure_limit', models.PositiveIntegerField(default=10, help_text='Number of wrong password/MFA attempts required before this stage blocks the user.', verbose_name='Failed attempts before block')),
                ('block_seconds', models.PositiveIntegerField(default=300, help_text='How long the login/MFA check is blocked after this stage triggers.', verbose_name='Block duration (seconds)')),
                ('repeat_count', models.PositiveIntegerField(default=1, help_text='How many lockouts should use this stage before moving to the next stage. Use 0 on the final stage to repeat forever.', verbose_name='Repeat count')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('site_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_lockout_stages', to='kb.sitesetting')),
            ],
            options={
                'verbose_name': 'Authentication lockout policy stage',
                'verbose_name_plural': 'Authentication lockout policy stages',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SuggestedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_username_snapshot', models.CharField(blank=True, max_length=150)),
                ('author_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('author_email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('author_account_type_snapshot', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('failed', 'Pending failed'), ('published', 'Published')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Date and time when this article was approved for public display.', null=True, verbose_name='Approved at')),
                ('review_notes', models.TextField(blank=True, help_text='Current admin feedback shown to the article owner while the article is in Draft or Pending failed status.', verbose_name='Current pending failed comments')),
                ('review_notes_history', models.JSONField(blank=True, default=list, help_text='Historical review feedback entries from previous rejection/resubmission rounds.', verbose_name='Pending failed comments history')),
                ('pending_update_title', models.CharField(blank=True, help_text='Edited title waiting for admin approval. The published title remains unchanged until approval.', max_length=200, verbose_name='Pending update title')),
                ('pending_update_body', models.TextField(blank=True, help_text='Edited Markdown body waiting for admin approval. The published body remains unchanged until approval.', verbose_name='Pending update body')),
                ('pending_update_keywords', models.CharField(blank=True, help_text='Edited keywords waiting for admin approval.', max_length=500, verbose_name='Pending update keywords')),
                ('pending_update_image_assets', models.JSONField(blank=True, default=list, help_text='Images referenced by the pending update draft.', verbose_name='Pending update image assets')),
                ('update_status', models.CharField(choices=[('none', 'No pending update'), ('pending', 'Pending update'), ('failed', 'Update pending failed')], db_index=True, default='none', max_length=20, verbose_name='Update approval status')),
                ('update_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Update submitted at')),
                ('update_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Update reviewed at')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of unique session views for this article.')),
                ('filename', models.CharField(blank=True, max_length=255, unique=True)),
                ('raw_path', models.CharField(blank=True, max_length=500)),
                ('wiki_path', models.CharField(blank=True, max_length=500)),
                ('image_assets', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin user who approved this article for public display.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_articles', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suggested Article',
                'verbose_name_plural': 'Suggested Articles',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMFADevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=512)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kb_mfa_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User MFA device',
                'verbose_name_plural': 'User MFA devices',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('ldap_user', 'LDAP user'), ('ldap_admin', 'LDAP admin')], default='user', help_text='Admin/LDAP admin accounts can access Django admin when staff status is enabled.', max_length=20)),
                ('auth_source', models.CharField(choices=[('local', 'Local user'), ('ad', 'Active Directory user')], default='local', help_text='Controls whether the password is managed locally in Knowledge Repository or externally by Active Directory.', max_length=20)),
                ('can_access_main_site', models.BooleanField(default=True, help_text='Untick this to block the user from accessing the main wiki site.')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('da', 'Dansk'), ('es', 'Español'), ('zh-hans', '简体中文'), ('ru', 'Русский'), ('pt-br', 'Português do Brasil'), ('ja', '日本語'), ('fi', 'Suomi'), ('sv', 'Svenska'), ('tr', 'Türkçe'), ('fa', 'فارسی'), ('ms', 'Bahasa Melayu'), ('ta', 'தமிழ்'), ('fr', 'Français'), ('it', 'Italiano'), ('ko', '한국어'), ('id', 'Bahasa Indonesia'), ('th', 'ไทย'), ('vi', 'Tiếng Việt'), ('nl', 'Nederlands'), ('pl', 'Polski'), ('ar', 'العربية')], default='en', help_text='Preferred language for the main wiki user interface.', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kb_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Main Site User Profile',
                'verbose_name_plural': 'Main Site User Profiles',
            },
        ),
        migrations.CreateModel(
            name='ArticleImageUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(db_index=True, max_length=255, unique=True)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploader_username_snapshot', models.CharField(blank=True, db_index=True, max_length=150)),
                ('uploader_email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('uploader_account_type_snapshot', models.CharField(blank=True, max_length=50)),
                ('upload_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('upload_user_agent', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delete_reason', models.CharField(blank=True, choices=[('user_removed', 'Removed by uploader from editor'), ('admin_cleanup', 'Deleted by admin stray-file cleanup'), ('auto_cleanup', 'Deleted by automatic stray-file cleanup')], max_length=30)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Historical deleter ID snapshot only. Image deletion activity is appended into ActivityLog rather than editing this upload log row.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_article_images', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Historical uploader ID snapshot only. The username/email snapshot fields keep the log readable after the user account is changed or deleted.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uploaded_article_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article image upload log',
                'verbose_name_plural': 'Article image upload logs',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['filename'], name='kb_articlei_filenam_c7f6d4_idx'), models.Index(fields=['uploader_username_snapshot', '-uploaded_at'], name='kb_articlei_uploade_6e1e42_idx'), models.Index(fields=['-uploaded_at'], name='kb_articlei_uploade_5d2a0f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('password_success', 'Password login success'), ('password_failure', 'Password login failure'), ('pending_mfa', 'Pending MFA created'), ('mfa_setup_success', 'MFA setup success'), ('mfa_setup_failure', 'MFA setup failure'), ('mfa_verify_success', 'MFA verify success'), ('mfa_verify_failure', 'MFA verify failure'), ('mfa_reset_self', 'MFA reset by user'), ('mfa_reset_admin', 'MFA reset by admin'), ('auth_lockout_reset_admin', 'Authentication lockout reset by admin'), ('logout', 'Logout')], db_index=True, max_length=40)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('username', models.CharField(blank=True, db_index=True, max_length=255)),
                ('login_mode', models.CharField(blank=True, db_index=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Historical user ID snapshot only. This relation intentionally does not enforce a database constraint because audit logs must remain immutable when users are deleted.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='auth_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authentication activity log',
                'verbose_name_plural': 'Authentication activity logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'event_type'], name='kb_authacti_created_9c7968_idx'), models.Index(fields=['ip_address', '-created_at'], name='kb_authacti_ip_addr_f1d0bb_idx'), models.Index(fields=['username', '-created_at'], name='kb_authacti_usernam_0b8fd5_idx')],
            },
            bases=(kb.models.AppendOnlyAuditLogMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ArticleVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Helpful'), (-1, 'Not helpful')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_votes', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='kb.suggestedarticle')),
            ],
            options={
                'verbose_name': 'Article vote',
                'verbose_name_plural': 'Article votes',
                'ordering': ['-updated_at'],
                'unique_together': {('article', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('article_created', 'Article created'), ('article_updated', 'Article updated'), ('article_deleted', 'Article deleted'), ('article_status_changed', 'Article status changed'), ('article_submitted', 'Article submitted for approval'), ('article_approved', 'Article approved/published'), ('article_rejected', 'Article marked pending failed'), ('article_orphan_assigned', 'Orphan article assigned'), ('article_orphan_deleted', 'Orphan article deleted'), ('article_viewed', 'Article viewed'), ('vote_up', 'Article vote up'), ('vote_down', 'Article vote down'), ('vote_updated', 'Article vote changed'), ('vote_removed', 'Article vote removed'), ('image_uploaded', 'Article image uploaded'), ('image_deleted', 'Article image deleted'), ('ai_question', 'OpenKB AI question'), ('ai_rate_limited', 'OpenKB AI rate limited'), ('bulk_import', 'Bulk article import'), ('admin_tool_action', 'Admin tool action')], db_index=True, max_length=60)),
                ('username', models.CharField(blank=True, db_index=True, max_length=255)),
                ('article_title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('article_status', models.CharField(blank=True, db_index=True, max_length=40)),
                ('article_owner_user_id_snapshot', models.PositiveIntegerField(blank=True, db_index=True, help_text='Historical user ID of the account that owned the article when this log was created.', null=True, verbose_name='Article owner user ID snapshot')),
                ('article_owner_username_snapshot', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Article owner username snapshot')),
                ('article_owner_name_snapshot', models.CharField(blank=True, max_length=255, verbose_name='Article owner name snapshot')),
                ('article_owner_email_snapshot', models.EmailField(blank=True, max_length=254, verbose_name='Article owner email snapshot')),
                ('article_owner_account_type_snapshot', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Article owner account type snapshot')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Historical user ID snapshot only. This relation intentionally does not enforce a database constraint because audit logs must remain immutable when users are deleted.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(blank=True, db_constraint=False, help_text='Snapshot fields keep the audit trail after an article is deleted. This relation intentionally does not enforce a database constraint because audit logs are append-only.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_logs', to='kb.suggestedarticle')),
            ],
            options={
                'verbose_name': 'Activity log',
                'verbose_name_plural': 'Activity logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'event_type'], name='kb_activity_created_34f83d_idx'), models.Index(fields=['username', '-created_at'], name='kb_activity_usernam_e4c3d4_idx'), models.Index(fields=['article_title', '-created_at'], name='kb_activity_article_0387e8_idx'), models.Index(fields=['article_owner_username_snapshot', '-created_at'], name='kb_act_owner_cr_idx'), models.Index(fields=['ip_address', '-created_at'], name='kb_activity_ip_addr_709e8b_idx')],
            },
            bases=(kb.models.AppendOnlyAuditLogMixin, models.Model),
        ),
        migrations.RunPython(create_default_site_settings, remove_default_site_settings),
        migrations.RunPython(install_audit_log_triggers, remove_audit_log_triggers),
    ]
