# Generated by ChatGPT for DjOpenKB session timeout wording update.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0005_session_timeout_setting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesetting",
            name="session_timeout_days",
            field=models.PositiveIntegerField(
                default=30,
                verbose_name="User session timeout (days)",
                help_text=(
                    "Authenticated user sessions expire after this many days from sign-in. "
                    "After expiry, users are signed out and must log in again. "
                    "Set to 0 to expire the session when the browser closes."
                ),
            ),
        ),
    ]
