# Generated by ChatGPT patch for internal/private article visibility

from django.db import migrations, models
import django.utils.translation


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0012_regular_user_fallback_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestedarticle",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", django.utils.translation.gettext_lazy("Public article")),
                    ("internal", django.utils.translation.gettext_lazy("Internal article")),
                ],
                db_index=True,
                default="public",
                help_text=django.utils.translation.gettext_lazy(
                    "Public articles are visible to normal wiki users. Internal articles are visible only to users with internal article access."
                ),
                max_length=20,
                verbose_name=django.utils.translation.gettext_lazy("Article visibility"),
            ),
        ),
    ]
