# Generated by ChatGPT patch for published-article deletion approval workflow

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django.utils.translation


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0013_internal_article_visibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleDeletionRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", django.utils.translation.gettext_lazy("Pending deletion approval")), ("approved", django.utils.translation.gettext_lazy("Deletion approved")), ("rejected", django.utils.translation.gettext_lazy("Deletion rejected"))], db_index=True, default="pending", max_length=20)),
                ("reason", models.TextField(blank=True)),
                ("review_comment", models.TextField(blank=True)),
                ("article_title_snapshot", models.CharField(blank=True, db_index=True, max_length=255)),
                ("article_visibility_snapshot", models.CharField(blank=True, db_index=True, max_length=20)),
                ("article_status_snapshot", models.CharField(blank=True, db_index=True, max_length=20)),
                ("article_owner_username_snapshot", models.CharField(blank=True, db_index=True, max_length=255)),
                ("article_owner_email_snapshot", models.EmailField(blank=True, max_length=254)),
                ("requested_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("article", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deletion_requests", to="kb.suggestedarticle")),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="article_deletion_requests", to=settings.AUTH_USER_MODEL)),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_article_deletion_requests", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": django.utils.translation.gettext_lazy("Article deletion request"),
                "verbose_name_plural": django.utils.translation.gettext_lazy("Article deletion requests"),
                "ordering": ["-requested_at"],
            },
        ),
        migrations.AddIndex(
            model_name="articledeletionrequest",
            index=models.Index(fields=["status", "article_visibility_snapshot"], name="kb_delreq_status_vis_idx"),
        ),
        migrations.AddIndex(
            model_name="articledeletionrequest",
            index=models.Index(fields=["-requested_at", "status"], name="kb_delreq_req_status_idx"),
        ),
    ]
