# Generated by ChatGPT patch for profile activity logging event labels.

from django.db import migrations, models
import django.utils.translation


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0014_article_deletion_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("article_created", django.utils.translation.gettext_lazy("Article created")),
                    ("article_updated", django.utils.translation.gettext_lazy("Article updated")),
                    ("article_deleted", django.utils.translation.gettext_lazy("Article deleted")),
                    ("article_deletion_requested", django.utils.translation.gettext_lazy("Article deletion requested")),
                    ("article_deletion_rejected", django.utils.translation.gettext_lazy("Article deletion rejected")),
                    ("article_status_changed", django.utils.translation.gettext_lazy("Article status changed")),
                    ("article_submitted", django.utils.translation.gettext_lazy("Article submitted for approval")),
                    ("article_approved", django.utils.translation.gettext_lazy("Article approved/published")),
                    ("article_rejected", django.utils.translation.gettext_lazy("Article marked pending failed")),
                    ("article_orphan_assigned", django.utils.translation.gettext_lazy("Orphan article assigned")),
                    ("article_orphan_deleted", django.utils.translation.gettext_lazy("Orphan article deleted")),
                    ("article_viewed", django.utils.translation.gettext_lazy("Article viewed")),
                    ("vote_up", django.utils.translation.gettext_lazy("Article vote up")),
                    ("vote_down", django.utils.translation.gettext_lazy("Article vote down")),
                    ("vote_updated", django.utils.translation.gettext_lazy("Article vote changed")),
                    ("vote_removed", django.utils.translation.gettext_lazy("Article vote removed")),
                    ("image_uploaded", django.utils.translation.gettext_lazy("Article image uploaded")),
                    ("image_deleted", django.utils.translation.gettext_lazy("Article image deleted")),
                    ("ai_question", django.utils.translation.gettext_lazy("OpenKB AI question")),
                    ("ai_rate_limited", django.utils.translation.gettext_lazy("OpenKB AI rate limited")),
                    ("bulk_import", django.utils.translation.gettext_lazy("Bulk article import")),
                    ("profile_email_updated", django.utils.translation.gettext_lazy("Profile email updated")),
                    ("profile_password_changed", django.utils.translation.gettext_lazy("Profile password changed")),
                    ("admin_tool_action", django.utils.translation.gettext_lazy("Admin tool action")),
                ],
                db_index=True,
                max_length=60,
            ),
        ),
    ]
