# Generated by ChatGPT patch for delayed article deletion queue.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django.utils.translation


ARTICLE_STATUS_CHOICES = [
    ("draft", django.utils.translation.gettext_lazy("Draft")),
    ("pending", django.utils.translation.gettext_lazy("Pending")),
    ("failed", django.utils.translation.gettext_lazy("Pending failed")),
    ("published", django.utils.translation.gettext_lazy("Published")),
    ("delete_queued", django.utils.translation.gettext_lazy("Deletion queued")),
]

ACTIVITY_EVENT_CHOICES = [
    ("article_created", django.utils.translation.gettext_lazy("Article created")),
    ("article_updated", django.utils.translation.gettext_lazy("Article updated")),
    ("article_deleted", django.utils.translation.gettext_lazy("Article deleted")),
    ("article_delete_queued", django.utils.translation.gettext_lazy("Article queued for deletion")),
    ("article_delete_restored", django.utils.translation.gettext_lazy("Article restored from deletion queue")),
    ("article_delete_purged", django.utils.translation.gettext_lazy("Article permanently deleted")),
    ("article_delete_auto_purged", django.utils.translation.gettext_lazy("Article auto-deleted from queue")),
    ("article_deletion_requested", django.utils.translation.gettext_lazy("Article deletion requested")),
    ("article_deletion_rejected", django.utils.translation.gettext_lazy("Article deletion rejected")),
    ("article_status_changed", django.utils.translation.gettext_lazy("Article status changed")),
    ("article_submitted", django.utils.translation.gettext_lazy("Article submitted for approval")),
    ("article_approved", django.utils.translation.gettext_lazy("Article approved/published")),
    ("article_rejected", django.utils.translation.gettext_lazy("Article marked pending failed")),
    ("article_orphan_assigned", django.utils.translation.gettext_lazy("Orphan article assigned")),
    ("article_orphan_deleted", django.utils.translation.gettext_lazy("Orphan article deleted")),
    ("article_viewed", django.utils.translation.gettext_lazy("Article viewed")),
    ("vote_up", django.utils.translation.gettext_lazy("Article vote up")),
    ("vote_down", django.utils.translation.gettext_lazy("Article vote down")),
    ("vote_updated", django.utils.translation.gettext_lazy("Article vote changed")),
    ("vote_removed", django.utils.translation.gettext_lazy("Article vote removed")),
    ("image_uploaded", django.utils.translation.gettext_lazy("Article image uploaded")),
    ("image_deleted", django.utils.translation.gettext_lazy("Article image deleted")),
    ("ai_question", django.utils.translation.gettext_lazy("OpenKB AI question")),
    ("ai_rate_limited", django.utils.translation.gettext_lazy("OpenKB AI rate limited")),
    ("bulk_import", django.utils.translation.gettext_lazy("Bulk article import")),
    ("profile_email_updated", django.utils.translation.gettext_lazy("Profile email updated")),
    ("profile_password_changed", django.utils.translation.gettext_lazy("Profile password changed")),
    ("admin_tool_action", django.utils.translation.gettext_lazy("Admin tool action")),
]


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kb", "0015_profile_activity_event_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestedarticle",
            name="status",
            field=models.CharField(choices=ARTICLE_STATUS_CHOICES, default="draft", max_length=20),
        ),
        migrations.AddField(
            model_name="suggestedarticle",
            name="deletion_previous_status",
            field=models.CharField(
                blank=True,
                choices=ARTICLE_STATUS_CHOICES,
                db_index=True,
                help_text="Original workflow status saved so the article can be restored from the deletion queue.",
                max_length=20,
                verbose_name="Previous status before deletion queue",
            ),
        ),
        migrations.AddField(
            model_name="suggestedarticle",
            name="deletion_queued_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deletion queued at"),
        ),
        migrations.AddField(
            model_name="suggestedarticle",
            name="deletion_queued_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="queued_article_deletions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deletion queued by",
            ),
        ),
        migrations.AddField(
            model_name="suggestedarticle",
            name="deletion_purge_after",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="After this time, the queued article can be permanently deleted by the scheduled cleanup.",
                null=True,
                verbose_name="Permanent deletion after",
            ),
        ),
        migrations.AddField(
            model_name="suggestedarticle",
            name="deletion_restored_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Deletion restored at"),
        ),
        migrations.AddField(
            model_name="suggestedarticle",
            name="deletion_restored_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="restored_article_deletions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deletion restored by",
            ),
        ),
        migrations.AddField(
            model_name="suggestedarticle",
            name="deletion_reason",
            field=models.TextField(blank=True, verbose_name="Deletion reason"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="article_deletion_queue_retention_days",
            field=models.PositiveIntegerField(
                default=7,
                help_text="How long deleted articles remain recoverable in My Profile → Admin tools → Deletion queue before permanent deletion. Default is 7 days. Minimum enforced by code is 1 day.",
                verbose_name="Article deletion queue retention (days)",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="event_type",
            field=models.CharField(choices=ACTIVITY_EVENT_CHOICES, db_index=True, max_length=60),
        ),
    ]
