# Generated by Django 6.0.5 on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0017_article_deletion_retention_zero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesetting",
            name="activity_log_retention_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text=(
                    "Article/vote/image/admin-tool/admin-site activity logs older than this many days "
                    "can be deleted by the cleanup command. Use 0 to keep general and admin activity logs indefinitely."
                ),
                verbose_name="General activity log retention (days)",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="can_access_main_site",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Legacy compatibility field. Use the built-in Active checkbox on the user "
                    "account to control whether the user can sign in."
                ),
            ),
        ),
    ]
