# Generated by Django 6.0.6 on 2026-06-23

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0018_sync_model_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="openkb_ai_prompt_limit_per_24_hours",
            field=models.PositiveIntegerField(
                default=50,
                help_text=(
                    "Maximum accepted Ask OpenKB AI questions per user in a fixed 24-hour window. "
                    "The first accepted question starts the window and later questions do not extend it. Default: 50."
                ),
                validators=[MinValueValidator(1), MaxValueValidator(1000)],
                verbose_name="OpenKB AI prompts per 24 hours",
            ),
        ),
    ]
