from django.urls import path, re_path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("suggest/", views.suggest, name="suggest"),
    path("set-language/", views.set_site_language, name="set_site_language"),
    path("profile/", views.profile, name="profile"),
    path("profile/articles/", views.edit_my_suggestions, name="edit_my_suggestions"),
    path("profile/update/", views.update_profile, name="update_profile"),
    path("profile/change-password/", views.change_password, name="change_password"),
    path("mfa/setup/", views.mfa_setup, name="mfa_setup"),
    path("mfa/verify/", views.mfa_verify, name="mfa_verify"),
    path("mfa/reset/", views.reset_mfa, name="reset_mfa"),
    path("profile/admin/clean-stray-upload-files/", views.clean_stray_upload_files, name="clean_stray_upload_files"),
    path("profile/admin/clean-stray-images/", views.clean_stray_upload_files, name="clean_stray_images"),
    path("profile/admin/bulk-articles/", views.admin_bulk_articles, name="admin_bulk_articles"),
    path("profile/admin/bulk-articles/export/", views.export_articles_zip, name="export_articles_zip"),
    path("profile/admin/bulk-articles/import/", views.import_articles_zip, name="import_articles_zip"),
    path("profile/admin/pending-articles/", views.manage_pending_articles, name="manage_pending_articles"),
    path("profile/admin/orphan-articles/", views.manage_orphan_articles, name="manage_orphan_articles"),
    path("profile/articles/<int:article_id>/edit/", views.edit_suggestion, name="edit_suggestion"),
    path("profile/articles/<int:article_id>/delete/", views.delete_suggestion, name="delete_suggestion"),
    path("search/", views.search_articles, name="search"),
    path("ask-openkb-ai/", views.ask_openkb_ai, name="ask_openkb_ai"),
    path("articles/<int:article_id>/", views.article_detail, name="article_detail"),
    path("articles/<int:article_id>/vote/", views.vote_article, name="vote_article"),
    path("article-image-upload/", views.upload_article_image, name="upload_article_image"),
    path("article-image-delete/", views.delete_article_image, name="delete_article_image"),
    path("wiki/uploads/<path:filename>", views.serve_article_image, name="serve_article_image"),
    re_path(r"^wiki/(?P<wiki_path>.+)$", views.wiki_detail, name="wiki_detail"),
]
