import os
import io
import json
import logging
import re
import shutil
import subprocess
import sys
import time
import uuid
import zipfile
from datetime import datetime
from functools import wraps
from pathlib import Path

import bleach
import markdown
from PIL import Image, UnidentifiedImageError
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.views import LoginView
from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count, F, Q
from django.http import FileResponse, Http404, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone, translation
from django.utils.translation import gettext as _
from django.utils.http import url_has_allowed_host_and_scheme
from django.views.decorators.http import require_POST

from ..models import ActivityLog, ArticleImageUploadLog, ArticleVote, SuggestedArticle, UserProfile, SiteSetting, UserMFADevice, normalize_article_title
from ..mfa import user_requires_mfa
from ..permissions import (
    PERM_ADD_ARTICLES,
    PERM_MANAGE_ARTICLES,
    PERM_USE_ADMIN_TOOLS,
    PERM_VIEW_ARTICLES,
    role_permissions_summary,
    user_has_disabled_role,
    user_can_add_articles,
    user_can_manage_articles,
    user_can_use_admin_tools as permission_user_can_use_admin_tools,
    user_can_view_articles,
    user_can_view_dislike_counts,
    user_can_vote_articles,
)


IGNORED_WIKI_NAMES = {"AGENTS.md", "log.md", "index.md", "README.md"}
DJANGO_ARTICLE_SOURCE_MARKER = "generated_by: django-suggested-article"

# Small image files that users paste/upload into suggested Markdown articles.
# These are served through the protected /wiki/uploads/<filename> view, not by
# exposing the uploads directory directly.
ALLOWED_ARTICLE_IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif", ".webp"}
ALLOWED_ARTICLE_IMAGE_FORMATS = {
    "PNG": {"extension": ".png", "content_type": "image/png"},
    "JPEG": {"extension": ".jpg", "content_type": "image/jpeg"},
    "JPG": {"extension": ".jpg", "content_type": "image/jpeg"},
    "GIF": {"extension": ".gif", "content_type": "image/gif"},
    "WEBP": {"extension": ".webp", "content_type": "image/webp"},
}
MAX_ARTICLE_IMAGE_SIZE_BYTES = 2 * 1024 * 1024
MAX_ARTICLE_IMAGE_PIXELS = 16_000_000
ARTICLE_IMAGE_RE = re.compile(r"!\[[^\]]*\]\(/wiki/uploads/([^)/?#]+)(?:[?#][^)]*)?\)")

logger = logging.getLogger(__name__)


def remove_openkb_internal_metadata(markdown_text):
    """Remove Django/OpenKB sync metadata before public display/search/AI snippets.

    The Markdown source files keep small internal markers so Django can reconcile
    generated files, but those markers should never appear in search results,
    article snippets, or OpenKB AI responses. This also handles already-flattened
    variants such as "!generated by: django suggested article; article id: ...".
    """
    text = markdown_text or ""

    # Remove the original hidden marker comment.
    text = re.sub(
        r"^\s*<!--\s*generated[_\s-]*by\s*:\s*django[-_\s]*suggested[-_\s]*article[^>]*-->\s*",
        "",
        text,
        flags=re.IGNORECASE | re.MULTILINE,
    )

    # Remove any leaked/plain-text version of that marker from search/AI output.
    text = re.sub(
        r"^\s*!?\s*generated[_\s-]*by\s*:\s*django[-_\s]*suggested[-_\s]*article\s*;?\s*article[_\s-]*id\s*:\s*[^\r\n]+\s*",
        "",
        text,
        flags=re.IGNORECASE | re.MULTILINE,
    )

    # Remove generated sync front matter from OpenKB summaries if it is ever
    # shown directly. Keep normal user-written front matter untouched.
    text = re.sub(
        r"^---\s*\n(?=[\s\S]*?generated[_\s-]*by\s*:\s*django-openkb-sync)(?:.|\n)*?---\s*\n?",
        "",
        text,
        flags=re.IGNORECASE,
    )

    return text.lstrip("\ufeff\n\r ")


SEARCH_STOPWORDS = {
    "a", "an", "and", "are", "as", "at", "be", "by", "can", "do", "does",
    "for", "from", "how", "i", "in", "is", "it", "me", "my", "of", "on",
    "or", "our", "the", "this", "to", "was", "we", "what", "when", "where",
    "which", "who", "why", "with", "you", "your",
    # Chat filler / greetings should not make Ask OpenKB AI recommend random
    # articles just because words like "there" appear in article bodies.
    "hi", "hello", "hey", "there", "still", "alive", "thanks", "thank",
    "please", "pls", "ok", "okay", "yo",
}


def slugify_title(title):
    slug = title.strip().lower()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    slug = slug.strip("-")
    return slug or "untitled"


def find_duplicate_article_by_title(title, exclude_pk=None):
    """Return an existing article with the same normalized title, if any."""
    normalized_title = normalize_article_title(title)
    if not normalized_title:
        return None

    queryset = SuggestedArticle.objects.all()
    if exclude_pk:
        queryset = queryset.exclude(pk=exclude_pk)

    for article in queryset.only("id", "title"):
        if normalize_article_title(article.title) == normalized_title:
            return article
    return None


def duplicate_title_error_message(title):
    return _("An article with the title ‘%(title)s’ already exists. Please use a different title.") % {"title": title}


def get_review_notes_history(article):
    """Return admin review-note history newest first for templates.

    User resubmission events only cleared the current comment and repeated the
    same admin note in the history. Hide those entries so authors/admins only
    see the actual admin review comments.
    """
    history = article.review_notes_history or []
    if not isinstance(history, list):
        return []

    hidden_actions = {"resubmitted", "update_resubmitted"}
    visible_history = [
        entry for entry in history
        if not isinstance(entry, dict) or entry.get("action") not in hidden_actions
    ]
    return list(reversed(visible_history))


def get_safe_return_url(request, fallback_view_name="edit_my_suggestions"):
    """Return a safe local URL for edit/delete flows.

    This lets the same article edit/delete views send users back to the page
    they came from, such as Manage pending articles for admins or Edit my
    articles for owners, without allowing open redirects.
    """
    candidate = (request.POST.get("next") or request.GET.get("next") or "").strip()
    if candidate and url_has_allowed_host_and_scheme(
        candidate,
        allowed_hosts={request.get_host()},
        require_https=request.is_secure(),
    ):
        return candidate
    return reverse(fallback_view_name)


def user_is_site_admin(user):
    """Return True for users allowed to use full Knowledge Repository admin tools."""
    return permission_user_can_use_admin_tools(user)


def user_can_review_articles(user):
    """Return True for users allowed to review/manage pending article approvals."""
    return user_can_manage_articles(user)


def user_can_manage_article(user, article):
    """Return True when a user may edit or review this article.

    Writers may edit only their own articles. Article Managers may review/edit
    articles that are in an approval/review workflow. Admin Users may manage all
    articles. Deletion uses ``user_can_delete_article`` because reviewers should
    not automatically be able to delete other users' submissions.
    """
    if not article or not getattr(user, "is_authenticated", False) or not user.is_active:
        return False

    if user_can_use_admin_tools(user):
        return True

    if article.owner_id == user.pk and user_can_add_articles(user):
        return True

    if user_can_manage_articles(user):
        return bool(
            article.status in {SuggestedArticle.Status.PENDING, SuggestedArticle.Status.FAILED}
            or article.update_status in {SuggestedArticle.UpdateStatus.PENDING, SuggestedArticle.UpdateStatus.FAILED}
        )

    return False


def user_can_delete_article(user, article):
    """Return True when a user may delete an article.

    Admin Users may delete any article. Article owners with writer permission may
    delete their own articles. Article Managers can review/edit/approve/reject
    pending items, but cannot delete other users' articles unless they are also
    Admin Users.
    """
    if not article or not getattr(user, "is_authenticated", False) or not user.is_active:
        return False
    if user_can_use_admin_tools(user):
        return True
    return bool(article.owner_id == user.pk and user_can_add_articles(user))


def user_owns_article(user, article):
    """Return True only for the active authenticated owner of an article."""
    return bool(
        article
        and getattr(user, "is_authenticated", False)
        and user.is_active
        and article.owner_id == user.pk
    )


def require_article_manager(user, article):
    """Fail closed when the current user is not allowed to manage the article."""
    if not user_can_manage_article(user, article):
        raise Http404("Article not found")
    return True


def require_site_admin(user):
    """Fail closed when the current user is not allowed to use admin tools."""
    if not user_can_use_admin_tools(user):
        raise Http404("Page not found")
    return True


def allowed_article_edit_actions_for(user, article):
    """Return the exact form actions allowed for this user/article state.

    This protects the edit endpoint from forged POST actions. Templates hide
    buttons, but the view must still enforce the server-side rule. If a user has
    both Article Writer and Article Manager, owner/writer actions are preserved
    for the user's own articles instead of being swallowed by the manager role.
    """
    if not user_can_manage_article(user, article):
        return set()

    if user_can_use_admin_tools(user):
        return {"save", ""}

    if user_owns_article(user, article) and user_can_add_articles(user):
        if article.status == SuggestedArticle.Status.PUBLISHED:
            # Owners cannot overwrite a published article directly. They may save a
            # private update draft, submit it for approval, or discard it.
            return {"save_update_draft", "submit_update", "revert_published"}

        # Draft/failed articles can be kept as draft or submitted for approval.
        return {"draft", "submit"}

    if user_can_manage_articles(user):
        # Article Managers review through the status dropdown and Save button.
        # Managers reach this view from Manage pending articles.
        return {"save", ""}

    return set()


def validate_article_edit_action(user, article, submit_action):
    """Raise 404 for tampered edit actions that the user/role cannot perform."""
    submit_action = (submit_action or "save").strip()
    if submit_action not in allowed_article_edit_actions_for(user, article):
        raise Http404("Article action not allowed")
    return submit_action


def allowed_article_statuses_for_admin_edit(article):
    """Return statuses an admin may set for the current article edit flow."""
    if (
        article.status == SuggestedArticle.Status.PUBLISHED
        and article.update_status == SuggestedArticle.UpdateStatus.PENDING
    ):
        # Reviewing a pending update should only approve or reject that update.
        # It must not accidentally hide the already-published article.
        return {SuggestedArticle.Status.PUBLISHED, SuggestedArticle.Status.FAILED}

    return {
        SuggestedArticle.Status.DRAFT,
        SuggestedArticle.Status.PENDING,
        SuggestedArticle.Status.FAILED,
        SuggestedArticle.Status.PUBLISHED,
    }


def validate_admin_requested_article_status(article, requested_status):
    """Raise 404 for forged/tampered admin status values."""
    requested_status = (requested_status or article.status).strip()
    if requested_status not in allowed_article_statuses_for_admin_edit(article):
        raise Http404("Article status not allowed")
    return requested_status


def init_openkb_storage():
    settings.OPENKB_DATA_DIR.mkdir(parents=True, exist_ok=True)
    settings.OPENKB_RAW_DIR.mkdir(parents=True, exist_ok=True)
    settings.OPENKB_WIKI_DIR.mkdir(parents=True, exist_ok=True)
    (settings.OPENKB_WIKI_DIR / "sources").mkdir(parents=True, exist_ok=True)
    (settings.OPENKB_WIKI_DIR / "summaries").mkdir(parents=True, exist_ok=True)
    (settings.OPENKB_WIKI_DIR / "concepts").mkdir(parents=True, exist_ok=True)

    index_file = settings.OPENKB_WIKI_DIR / "index.md"
    if not index_file.exists():
        index_file.write_text(
            "# Knowledge Base Index\n\n"
            "## Documents\n\n"
            "## Concepts\n\n"
            "## Explorations\n",
            encoding="utf-8",
        )


def get_openkb_uploads_dir():
    """Folder used for small images pasted into suggested Markdown articles."""
    upload_dir = settings.OPENKB_WIKI_DIR / "uploads"
    upload_dir.mkdir(parents=True, exist_ok=True)
    return upload_dir


def validate_article_image_upload(uploaded_file):
    """Return image metadata when an uploaded file is a safe supported image.

    Browser-reported content_type can be faked, so this verifies the actual file
    bytes with Pillow and only accepts PNG, JPG/JPEG, GIF, and WEBP.
    """
    original_suffix = Path(uploaded_file.name or "").suffix.lower()
    if original_suffix and original_suffix not in ALLOWED_ARTICLE_IMAGE_EXTENSIONS:
        raise ValidationError("Only PNG, JPG, GIF, or WEBP images are allowed.")

    if uploaded_file.size > MAX_ARTICLE_IMAGE_SIZE_BYTES:
        raise ValidationError("Image is too large. Maximum allowed size is 2 MB.")

    try:
        uploaded_file.seek(0)
        with Image.open(uploaded_file) as image:
            image.verify()
            detected_format = (image.format or "").upper()
            width, height = image.size
    except (UnidentifiedImageError, OSError, ValueError):
        raise ValidationError("The uploaded file is not a valid image.")
    finally:
        try:
            uploaded_file.seek(0)
        except Exception:
            pass

    image_info = ALLOWED_ARTICLE_IMAGE_FORMATS.get(detected_format)
    if not image_info:
        raise ValidationError("Only PNG, JPG, GIF, or WEBP images are allowed.")

    if width * height > MAX_ARTICLE_IMAGE_PIXELS:
        raise ValidationError("Image dimensions are too large. Please upload a smaller image.")

    return {
        "format": detected_format,
        "extension": image_info["extension"],
        "content_type": image_info["content_type"],
        "width": width,
        "height": height,
    }


def is_allowed_article_image_filename(filename):
    """Return True only for server-managed image filenames."""
    safe_name = safe_uploaded_filename(filename)
    if not safe_name or safe_name != filename:
        return False
    return Path(safe_name).suffix.lower() in ALLOWED_ARTICLE_IMAGE_EXTENSIONS


def uploaded_image_content_type(filename):
    suffix = Path(filename or "").suffix.lower()
    if suffix in {".jpg", ".jpeg"}:
        return "image/jpeg"
    if suffix == ".png":
        return "image/png"
    if suffix == ".gif":
        return "image/gif"
    if suffix == ".webp":
        return "image/webp"
    return "application/octet-stream"


def extract_article_image_filenames(markdown_text):
    """Return unique uploaded image filenames referenced in Markdown body."""
    seen = []
    for filename in ARTICLE_IMAGE_RE.findall(markdown_text or ""):
        if filename not in seen and "/" not in filename and "\\" not in filename:
            seen.append(filename)
    return seen


def get_article_image_upload_limit():
    """Return the admin-configured maximum number of images per article."""
    try:
        limit = int(getattr(SiteSetting.load(), "article_image_upload_limit", 50) or 0)
    except Exception:
        limit = 50
    return max(limit, 0)


def _bounded_site_setting_int(field_name, default, minimum, maximum):
    """Return an integer SiteSetting value clamped to a safe range."""
    try:
        value = int(getattr(SiteSetting.load(), field_name, default) or default)
    except Exception:
        return default

    if value < minimum:
        return minimum
    if value > maximum:
        return maximum
    return value


def get_articles_per_page():
    """Return article count for public search pagination and homepage columns."""
    return _bounded_site_setting_int("articles_per_page", default=10, minimum=5, maximum=100)


def article_image_limit_error_message(image_count=None, limit=None):
    limit = get_article_image_upload_limit() if limit is None else max(int(limit), 0)
    if limit <= 0:
        return _("Article image uploads are currently disabled by the administrator.")
    if image_count is None:
        return _("This article has reached the image upload limit of %(limit)s image(s).") % {"limit": limit}
    return _("This article has %(count)s image(s), but the maximum allowed is %(limit)s image(s). Please remove some images before saving.") % {"count": image_count, "limit": limit}


def validate_article_image_count(image_filenames):
    """Enforce the admin-configured image count limit for an article version."""
    limit = get_article_image_upload_limit()
    unique_images = []
    for filename in image_filenames or []:
        safe_name = safe_uploaded_filename(filename)
        if safe_name and safe_name not in unique_images:
            unique_images.append(safe_name)

    if limit <= 0 and unique_images:
        raise ValidationError(article_image_limit_error_message(limit=limit))
    if limit > 0 and len(unique_images) > limit:
        raise ValidationError(article_image_limit_error_message(len(unique_images), limit))
    return unique_images


def article_image_markdown(filename):
    return f"![image](/wiki/uploads/{filename})"


def article_image_url(filename):
    return f"/wiki/uploads/{filename}"


def delete_uploaded_image_file(filename):
    if not filename or "/" in filename or "\\" in filename or filename in {".", ".."}:
        return

    upload_dir = get_openkb_uploads_dir().resolve()
    file_path = (upload_dir / filename).resolve()

    try:
        file_path.relative_to(upload_dir)
    except ValueError:
        return

    if file_path.exists() and file_path.is_file():
        file_path.unlink()
        mark_article_image_deleted(
            filename,
            actor=None,
            reason=ArticleImageUploadLog.DeleteReason.AUTO_CLEANUP,
        )


def article_references_uploaded_filename(article, filename, include_pending_update=True):
    """Return True when an article references an uploaded image filename.

    Both committed article fields and pending-update fields are checked by
    default. This prevents the stray-upload cleaner from deleting images that
    are only used by a saved/submitted update waiting for admin approval.
    """
    if not filename:
        return False

    if filename in (article.image_assets or []):
        return True
    if filename in extract_article_image_filenames(article.body):
        return True

    if include_pending_update:
        if filename in (getattr(article, "pending_update_image_assets", None) or []):
            return True
        if filename in extract_article_image_filenames(getattr(article, "pending_update_body", "") or ""):
            return True

    return False


def image_is_used_by_other_article(filename, current_article=None):
    queryset = SuggestedArticle.objects.all()
    if current_article and current_article.pk:
        queryset = queryset.exclude(pk=current_article.pk)

    for article in queryset.only(
        "body",
        "image_assets",
        "pending_update_body",
        "pending_update_image_assets",
    ):
        if article_references_uploaded_filename(article, filename):
            return True
    return False


def sync_article_image_assets(article, old_assets=None):
    """Tie currently referenced uploaded images to this article and clean stale ones."""
    old_assets = set(old_assets if old_assets is not None else (article.image_assets or []))
    new_assets = set(extract_article_image_filenames(article.body))

    stale_assets = old_assets - new_assets
    for filename in stale_assets:
        # Do not delete an image if it is still referenced by this article's
        # pending-update draft/review fields or by any other article.
        if article_references_uploaded_filename(article, filename) or image_is_used_by_other_article(filename, current_article=article):
            continue
        delete_uploaded_image_file(filename)

    article.image_assets = sorted(new_assets)
    SuggestedArticle.objects.filter(pk=article.pk).update(image_assets=article.image_assets)
    return article.image_assets


def clear_committed_pending_uploads(request, image_assets):
    pending_uploads = request.session.get("pending_article_uploads", [])
    if not pending_uploads:
        return

    image_assets = set(image_assets or [])
    request.session["pending_article_uploads"] = [
        item for item in pending_uploads if item not in image_assets
    ]
    request.session.modified = True


def user_can_use_admin_tools(user):
    """Return True for users allowed to use profile-level admin maintenance tools."""
    return permission_user_can_use_admin_tools(user)


def article_view_required(view_func):
    """Require permission to view published internal articles/search/AI."""
    @wraps(view_func)
    @main_site_login_required
    def wrapper(request, *args, **kwargs):
        if not user_can_view_articles(request.user):
            raise Http404("Page not found")
        return view_func(request, *args, **kwargs)

    return wrapper


def article_add_required(view_func):
    """Require permission to create/maintain own article submissions."""
    @wraps(view_func)
    @main_site_login_required
    def wrapper(request, *args, **kwargs):
        if not user_can_add_articles(request.user):
            raise Http404("Page not found")
        return view_func(request, *args, **kwargs)

    return wrapper


def article_image_editor_required(view_func):
    """Require article authoring or article review permission for editor uploads."""
    @wraps(view_func)
    @main_site_login_required
    def wrapper(request, *args, **kwargs):
        if not (user_can_add_articles(request.user) or user_can_manage_articles(request.user)):
            raise Http404("Page not found")
        return view_func(request, *args, **kwargs)

    return wrapper


def article_management_required(view_func):
    """Require permission to review/manage pending articles."""
    @wraps(view_func)
    @main_site_login_required
    def wrapper(request, *args, **kwargs):
        if not user_can_manage_articles(request.user):
            raise Http404("Page not found")
        return view_func(request, *args, **kwargs)

    return wrapper


def admin_tools_required(view_func):
    """Require normal site access plus explicit Knowledge Repository admin-tool permission.

    Anonymous users are still redirected to login by main_site_login_required.
    Logged-in non-admin users receive 404 so admin-tool route discovery is less
    useful to scanners such as Gobuster.
    """
    @wraps(view_func)
    @main_site_login_required
    def wrapper(request, *args, **kwargs):
        if not user_can_use_admin_tools(request.user):
            raise Http404("Page not found")
        return view_func(request, *args, **kwargs)

    return wrapper


def extract_uploaded_file_filenames_from_text(text):
    """Find /wiki/uploads/<filename> references from Markdown or rendered HTML text."""
    if not text:
        return set()

    filenames = set(extract_article_image_filenames(text))

    # Also catch HTML img src or plain pasted URLs such as:
    # /wiki/uploads/example.png, http://host/wiki/uploads/example.png
    for filename in re.findall(r"/wiki/uploads/([A-Za-z0-9._-]+)", text):
        if filename and "/" not in filename and "\\" not in filename:
            filenames.add(filename)

    return filenames


def get_all_referenced_uploaded_files():
    """Return uploaded filenames still referenced by articles or Markdown files."""
    referenced = set()

    # 1) Trust Django article records first. This covers draft/published articles,
    # published-update drafts/reviews, and images tracked in image asset fields.
    for article in SuggestedArticle.objects.only(
        "body",
        "image_assets",
        "pending_update_body",
        "pending_update_image_assets",
    ):
        referenced.update(article.image_assets or [])
        referenced.update(extract_uploaded_file_filenames_from_text(article.body))
        referenced.update(article.pending_update_image_assets or [])
        referenced.update(extract_uploaded_file_filenames_from_text(article.pending_update_body))

    # 2) Also scan all OpenKB wiki Markdown files. This protects manually added
    # Markdown files or files edited outside Django.
    wiki_dir = settings.OPENKB_WIKI_DIR
    if wiki_dir.exists():
        for markdown_file in wiki_dir.rglob("*.md"):
            try:
                text = markdown_file.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            referenced.update(extract_uploaded_file_filenames_from_text(text))

    return {
        filename for filename in referenced
        if filename and "/" not in filename and "\\" not in filename
    }


def get_stray_upload_cleanup_min_age_minutes():
    """Return cleanup age threshold from Django Admin site settings."""
    try:
        value = SiteSetting.load().stray_upload_cleanup_min_age_minutes
    except Exception:
        value = 1440

    try:
        value = int(value)
    except (TypeError, ValueError):
        value = 1440

    return max(value, 0)



def get_article_image_upload_log(filename):
    """Return the upload audit row for a generated article image filename."""
    filename = safe_uploaded_filename(filename)
    if not filename:
        return None

    try:
        return ArticleImageUploadLog.objects.select_related("uploaded_by", "deleted_by").filter(filename=filename).first()
    except Exception:
        logger.exception("Unable to read article image upload log for %s", filename)
        return None


def mark_article_image_deleted(filename, actor=None, reason="", record_activity=True):
    """Record image deletion without editing the original upload log.

    ArticleImageUploadLog is append-only and records the upload event. Deletion
    events are appended into ActivityLog instead of updating deleted_at/delete_reason
    on the original upload row. Views that already call log_activity() can pass
    record_activity=False to avoid duplicate ActivityLog rows.
    """
    filename = safe_uploaded_filename(filename)
    if not filename:
        return

    logger.info(
        "Article image deletion noted without editing append-only upload log: filename=%s actor=%s reason=%s",
        filename,
        getattr(actor, "pk", None),
        reason or "",
    )

    if not record_activity:
        return

    try:
        actor_is_authenticated = bool(getattr(actor, "is_authenticated", False))
        ActivityLog.objects.create(
            event_type=ActivityLog.EventType.IMAGE_DELETED,
            user=actor if actor_is_authenticated else None,
            username=actor.get_username() if actor_is_authenticated else "",
            details={
                "filename": filename,
                "reason": reason or "",
                "source": "append_only_image_delete_marker",
            },
        )
    except Exception:
        logger.exception("Unable to append image deletion ActivityLog for %s", filename)

def find_stray_uploaded_files(min_age_minutes=1440):
    """Return uploaded files that are not referenced anywhere.

    The minimum age protects someone who is currently editing an article: a
    file uploaded seconds ago may not be saved into Markdown yet.
    """
    init_openkb_storage()
    upload_dir = get_openkb_uploads_dir().resolve()
    referenced = get_all_referenced_uploaded_files()
    cutoff_time = timezone.now().timestamp() - (min_age_minutes * 60)

    stray_files = []

    if not upload_dir.exists():
        return stray_files

    for file_path in upload_dir.iterdir():
        if not file_path.is_file():
            continue

        filename = file_path.name
        if filename in referenced:
            continue

        try:
            stat = file_path.stat()
        except OSError:
            continue

        if stat.st_mtime > cutoff_time:
            continue

        extension = file_path.suffix.lower().lstrip(".") or "(no extension)"
        is_previewable_image = file_path.suffix.lower() in {".png", ".jpg", ".jpeg", ".gif", ".webp"}

        upload_log = get_article_image_upload_log(filename)
        uploader_display = ""
        uploader_email = ""
        uploader_account_type = ""
        uploaded_at = None

        if upload_log:
            uploader_display = upload_log.uploader_display
            uploader_email = upload_log.uploader_email_snapshot
            uploader_account_type = upload_log.uploader_account_type_snapshot
            uploaded_at = upload_log.uploaded_at

        stray_files.append({
            "filename": filename,
            "url": article_image_url(filename),
            "extension": extension,
            "is_previewable_image": is_previewable_image,
            "size_bytes": stat.st_size,
            "size_kb": round(stat.st_size / 1024, 1),
            "modified_at": datetime.fromtimestamp(stat.st_mtime),
            "path": file_path,
            "upload_log": upload_log,
            "uploader_display": uploader_display,
            "uploader_email": uploader_email,
            "uploader_account_type": uploader_account_type,
            "uploaded_at": uploaded_at,
        })
    stray_files.sort(key=lambda item: item["modified_at"], reverse=True)
    return stray_files


def clean_wiki_title(file_path):
    return file_path.stem.replace("-", " ").replace("_", " ").title()


def format_user_for_markdown(user):
    full_name = user.get_full_name().strip()
    if full_name and user.email:
        return f"{full_name} ({user.email})"
    if user.email:
        return user.email
    return user.get_username()


def build_article_markdown(article):
    keyword_line = ""
    if article.keywords:
        keyword_line = f"\n\n**Keywords:** {article.keywords}"

    article_id = getattr(article, "id", "") or "export"
    return (
        f"<!-- {DJANGO_ARTICLE_SOURCE_MARKER}; article_id: {article_id} -->\n"
        f"# {article.title}\n\n"
        f"{article.body}\n"
        f"{keyword_line}\n"
    )


def plain_markdown_excerpt(markdown_text, max_length=260):
    """Create a short plain-text summary from Markdown for the OpenKB AI index."""
    text = remove_openkb_internal_metadata(markdown_text)

    # Remove YAML front matter, HTML comments, images, links, and common Markdown symbols.
    text = re.sub(r"^---.*?---", " ", text, flags=re.DOTALL).strip()
    text = re.sub(r"<!--.*?-->", " ", text, flags=re.DOTALL)
    text = re.sub(r"!\[[^\]]*\]\([^)]+\)", " ", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"\*\*Keywords:\*\*\s*.*", " ", text, flags=re.IGNORECASE)
    text = re.sub(r"[#>*_`~|\-]+", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    if not text:
        return "Django published OpenKB article."

    if len(text) > max_length:
        text = text[:max_length].rsplit(" ", 1)[0].rstrip() + "..."

    return text


def extract_markdown_title(file_path, raw_markdown):
    """Use the first Markdown H1 as the AI title, otherwise fallback to filename."""
    for line in (raw_markdown or "").splitlines():
        line = line.strip()
        if line.startswith("# "):
            return line[2:].strip() or clean_wiki_title(file_path)
    return clean_wiki_title(file_path)


def extract_index_section(existing_text, heading):
    """Preserve non-Django OpenKB sections when rebuilding index.md."""
    lines = existing_text.splitlines()
    start = None

    for index, line in enumerate(lines):
        if line.strip() == heading:
            start = index + 1
            break

    if start is None:
        return ""

    end = len(lines)
    for index in range(start, len(lines)):
        if lines[index].startswith("## "):
            end = index
            break

    return "\n".join(lines[start:end]).strip()


def ensure_article_filename(article):
    """Ensure every SuggestedArticle has a stable Markdown filename."""
    if article.filename:
        return article.filename

    timestamp_slug = timezone.localtime(article.created_at or timezone.now()).strftime("%Y%m%d-%H%M%S")
    base_slug = slugify_title(article.title)
    candidate = f"{timestamp_slug}-{base_slug}.md"
    counter = 2
    while SuggestedArticle.objects.filter(filename=candidate).exclude(pk=article.pk).exists():
        candidate = f"{timestamp_slug}-{base_slug}-{counter}.md"
        counter += 1

    article.filename = candidate
    return article.filename


def source_file_is_django_managed(path):
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")[:500]
    except OSError:
        return False
    return DJANGO_ARTICLE_SOURCE_MARKER in text


def reconcile_openkb_article_files():
    """Reconcile OpenKB files from the Django database as the source of truth.

    - Every Django article gets a raw Markdown file.
    - Only published Django articles get a public wiki/sources file.
    - Unpublished Django articles have their source file removed.
    - Old source files generated by this Django integration are removed when the
      database article no longer exists. Manually-created OpenKB source files are
      left untouched.
    """
    init_openkb_storage()

    sources_dir = settings.OPENKB_WIKI_DIR / "sources"
    managed_filenames = set()

    for article in SuggestedArticle.objects.all().order_by("id"):
        ensure_article_filename(article)
        write_article_files(article, sync_ai=False, mark_ai_stale=False)
        managed_filenames.add(article.filename)

    for source_path in sources_dir.glob("*.md"):
        if source_path.name in managed_filenames or source_path.name in IGNORED_WIKI_NAMES:
            continue
        if source_file_is_django_managed(source_path):
            try:
                source_path.unlink()
            except OSError as error:
                logger.warning("Could not remove stale Django OpenKB source %s: %s", source_path, error)


def write_openkb_django_sync_state(documents):
    """Write a small audit file so OpenKB/Django sync state can be inspected."""
    state_dir = settings.OPENKB_DATA_DIR / ".openkb"
    state_dir.mkdir(parents=True, exist_ok=True)
    state = {
        "generated_by": "django-openkb-sync",
        "synced_at": timezone.localtime(timezone.now()).isoformat(),
        "published_document_count": len(documents),
        "documents": documents,
    }
    (state_dir / "django_sync_state.json").write_text(
        json.dumps(state, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def get_openkb_ai_sync_state_path():
    """Return the lightweight state file used to decide whether AI sync is needed."""
    state_dir = settings.OPENKB_DATA_DIR / ".openkb"
    state_dir.mkdir(parents=True, exist_ok=True)
    return state_dir / "django_ai_sync_state.json"


def write_openkb_ai_sync_state(stale, reason, extra=None):
    """Persist whether Ask OpenKB AI needs a fresh Django/OpenKB sync."""
    init_openkb_storage()
    now_iso = timezone.localtime(timezone.now()).isoformat()
    state = {
        "generated_by": "django-openkb-ai-sync-state",
        "stale": bool(stale),
        "reason": reason,
        "updated_at": now_iso,
    }

    existing = read_openkb_ai_sync_state(default={})
    if stale:
        state["stale_since"] = existing.get("stale_since") or now_iso
        if existing.get("last_synced_at"):
            state["last_synced_at"] = existing.get("last_synced_at")
    else:
        state["last_synced_at"] = now_iso

    if extra:
        state.update(extra)

    get_openkb_ai_sync_state_path().write_text(
        json.dumps(state, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    return state


def read_openkb_ai_sync_state(default=None):
    """Read the on-demand AI sync state file."""
    path = get_openkb_ai_sync_state_path()
    if not path.exists():
        return default if default is not None else {"stale": True, "reason": "No AI sync state found."}

    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return default if default is not None else {"stale": True, "reason": "AI sync state could not be read."}


def mark_openkb_ai_stale(reason="Article content changed."):
    """Mark OpenKB AI index as needing a rebuild later.

    This is intentionally cheap and is used during article create/edit/publish/delete
    flows so admin redirects stay fast. The actual full sync happens only when
    someone asks OpenKB AI or when the management command is run manually.
    """
    try:
        write_openkb_ai_sync_state(True, reason)
    except Exception as error:
        logger.warning("Could not mark OpenKB AI sync state as stale: %s", error)


def openkb_ai_sync_is_stale():
    """Return True when the AI index should be rebuilt before answering."""
    state = read_openkb_ai_sync_state()
    if state.get("stale", True):
        return True

    wiki_dir = settings.OPENKB_WIKI_DIR
    index_file = wiki_dir / "index.md"
    summaries_dir = wiki_dir / "summaries"
    if not index_file.exists() or not summaries_dir.exists():
        return True

    return False


def ensure_openkb_ai_synced():
    """Synchronize OpenKB AI files only when article changes made them stale."""
    if openkb_ai_sync_is_stale():
        logger.info("OpenKB AI index is stale; syncing on demand before answering.")
        sync_openkb_ai_index()
    else:
        logger.info("OpenKB AI index is fresh; skipping sync before answering.")


def sync_openkb_ai_index():
    """Make Ask OpenKB AI aware of Django-published source articles.

    OpenKB query starts from wiki/index.md and wiki/summaries/*.md.
    Django writes published articles directly into wiki/sources/*.md, so this
    function creates lightweight summaries and rebuilds index.md from sources.
    No LLM call is made here, so it is safe to run before each AI query.
    """
    init_openkb_storage()
    reconcile_openkb_article_files()

    wiki_dir = settings.OPENKB_WIKI_DIR
    sources_dir = wiki_dir / "sources"
    summaries_dir = wiki_dir / "summaries"
    index_file = wiki_dir / "index.md"

    sources_dir.mkdir(parents=True, exist_ok=True)
    summaries_dir.mkdir(parents=True, exist_ok=True)

    existing_index = ""
    if index_file.exists():
        existing_index = index_file.read_text(encoding="utf-8", errors="ignore")

    existing_concepts = extract_index_section(existing_index, "## Concepts")
    existing_explorations = extract_index_section(existing_index, "## Explorations")

    # Remove old Django-generated summaries so deleted/unpublished articles vanish
    # from AI results. Keep any non-generated summaries that may exist.
    for summary_file in summaries_dir.glob("*.md"):
        try:
            text = summary_file.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if "generated_by: django-openkb-sync" in text:
            try:
                summary_file.unlink()
            except OSError:
                pass

    documents = []

    for source_path in sorted(sources_dir.rglob("*.md")):
        if source_path.name in IGNORED_WIKI_NAMES:
            continue

        try:
            raw_markdown = source_path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue

        relative_source = source_path.relative_to(wiki_dir).as_posix()
        doc_name = source_path.stem
        summary_relative = f"summaries/{doc_name}"
        title = extract_markdown_title(source_path, raw_markdown)
        brief = plain_markdown_excerpt(raw_markdown)

        summary_text = (
            "---\n"
            "doc_type: short\n"
            "generated_by: django-openkb-sync\n"
            f"full_text: {relative_source}\n"
            "---\n\n"
            f"# {title}\n\n"
            f"{brief}\n"
        )

        (summaries_dir / f"{doc_name}.md").write_text(summary_text, encoding="utf-8")

        documents.append({
            "source_relative": relative_source,
            "summary_relative": f"{summary_relative}.md",
            "title": title,
            "brief": brief,
            "django_managed": DJANGO_ARTICLE_SOURCE_MARKER in raw_markdown,
        })

    index_lines = [
        "# Knowledge Base Index",
        "",
        "## Documents",
    ]

    if documents:
        for item in documents:
            index_lines.append(
                f"- [[{item['summary_relative'].removesuffix('.md')}]] (short) — {item['title']}: {item['brief']}"
            )
    else:
        index_lines.append("")

    index_lines.extend(["", "## Concepts"])
    if existing_concepts:
        index_lines.extend(existing_concepts.splitlines())
    else:
        index_lines.append("")

    index_lines.extend(["", "## Explorations"])
    if existing_explorations:
        index_lines.extend(existing_explorations.splitlines())
    else:
        index_lines.append("")

    index_file.write_text("\n".join(index_lines).rstrip() + "\n", encoding="utf-8")
    write_openkb_django_sync_state(documents)
    write_openkb_ai_sync_state(
        False,
        "OpenKB AI index synced.",
        {"published_document_count": len(documents)},
    )


def prepare_article_display_markdown(raw_markdown, title, suggested=None):
    """Remove Django-generated wrapper Markdown from public article display.

    SuggestedArticle files are saved with a leading H1 title and a trailing
    **Keywords:** metadata line so the Markdown file is self-contained.
    The public article page already displays the title and keywords in the
    OpenKB layout, so remove those generated lines to avoid duplicate UI text.
    """
    cleaned = remove_openkb_internal_metadata(raw_markdown)

    # Remove the first Markdown H1 only when it matches the article title.
    lines = cleaned.splitlines()
    if lines:
        first_line = lines[0].strip()
        if first_line.startswith("#"):
            heading_text = first_line.lstrip("#").strip()
            if heading_text.lower() == title.strip().lower():
                lines = lines[1:]
                while lines and not lines[0].strip():
                    lines = lines[1:]
                cleaned = "\n".join(lines)

    # Remove the generated keywords line from the body. Keywords are displayed
    # below the article details panel instead.
    if suggested and suggested.keywords:
        cleaned = re.sub(
            r"\n*\*\*Keywords:\*\*\s*.*\s*$",
            "",
            cleaned,
            flags=re.IGNORECASE,
        ).rstrip()

    return cleaned


def is_safe_article_upload_src(tag, name, value):
    """Allow only local /wiki/uploads/<safe-image-filename> image sources."""
    if name != "src":
        return False

    prefix = "/wiki/uploads/"
    if not value.startswith(prefix):
        return False

    filename = value[len(prefix):]
    return is_allowed_article_image_filename(filename)


def article_html_attribute_filter(tag, name, value):
    """Attribute allow-list for sanitized rendered Markdown."""
    if tag == "img":
        if name == "src":
            return is_safe_article_upload_src(tag, name, value)
        if name in {"alt", "title"}:
            return True
        return False

    if tag == "a":
        return name in {"href", "title"}

    if tag in {"code", "pre"}:
        return name == "class"

    if tag in {"th", "td"}:
        return name in {"align", "colspan", "rowspan"}

    if tag in {"h1", "h2", "h3", "h4", "h5", "h6"}:
        return name == "id"

    return False


def render_safe_markdown(markdown_text):
    """Render Markdown and sanitize raw HTML before displaying an article."""
    html = markdown.markdown(
        markdown_text or "",
        extensions=["fenced_code", "tables", "toc"],
        output_format="html5",
    )

    allowed_tags = set(bleach.sanitizer.ALLOWED_TAGS) | {
        "p", "br", "hr",
        "h1", "h2", "h3", "h4", "h5", "h6",
        "pre", "span",
        "table", "thead", "tbody", "tr", "th", "td",
        "img",
    }

    return bleach.clean(
        html,
        tags=allowed_tags,
        attributes=article_html_attribute_filter,
        protocols=["http", "https", "mailto"],
        strip=True,
    )


def write_article_files(article, sync_ai=False, mark_ai_stale=True):
    """Mirror a SuggestedArticle into OpenKB raw and public wiki/source Markdown files.

    Full AI summary/index rebuilds are intentionally not done here. Article save,
    publish, import, and delete flows should stay fast, so they only mark the AI
    index as stale. The heavier sync runs on demand when Ask OpenKB AI is used.
    The sync_ai argument is kept for backward compatibility with older callers.
    """
    init_openkb_storage()

    ensure_article_filename(article)

    raw_file_path = settings.OPENKB_RAW_DIR / article.filename
    sources_dir = settings.OPENKB_WIKI_DIR / "sources"
    wiki_file_path = sources_dir / article.filename

    markdown_content = build_article_markdown(article)

    raw_file_path.write_text(markdown_content, encoding="utf-8")

    if article.status == SuggestedArticle.Status.PUBLISHED:
        wiki_file_path.write_text(markdown_content, encoding="utf-8")
    elif wiki_file_path.exists():
        wiki_file_path.unlink()

    article.raw_path = raw_file_path.relative_to(settings.OPENKB_DATA_DIR).as_posix()
    article.wiki_path = f"sources/{article.filename}"

    SuggestedArticle.objects.filter(pk=article.pk).update(
        filename=article.filename,
        raw_path=article.raw_path,
        wiki_path=article.wiki_path,
    )

    if mark_ai_stale or sync_ai:
        mark_openkb_ai_stale("Article Markdown files changed.")


def delete_article_files(article):
    """Delete Markdown files and image assets for a user-owned article."""
    candidates = []

    if article.raw_path:
        candidates.append((settings.OPENKB_DATA_DIR / article.raw_path, settings.OPENKB_DATA_DIR))

    if article.wiki_path:
        candidates.append((settings.OPENKB_WIKI_DIR / article.wiki_path, settings.OPENKB_WIKI_DIR))

    for file_path, root_dir in candidates:
        file_path = file_path.resolve()
        root_dir = root_dir.resolve()

        try:
            file_path.relative_to(root_dir)
        except ValueError:
            continue

        if file_path.exists() and file_path.is_file():
            file_path.unlink()

    for filename in (article.image_assets or extract_article_image_filenames(article.body)):
        if not image_is_used_by_other_article(filename, current_article=article):
            delete_uploaded_image_file(filename)

    mark_openkb_ai_stale("Article Markdown files deleted.")


def get_article_metadata_by_wiki_path(wiki_path):
    try:
        return SuggestedArticle.objects.select_related("owner").get(
            wiki_path=wiki_path,
            status=SuggestedArticle.Status.PUBLISHED,
        )
    except SuggestedArticle.DoesNotExist:
        return None


def record_article_session_view(request, article):
    """Increment an article view count once per browser session.

    This prevents simple page refreshes from repeatedly increasing the counter.
    A different browser/session can still count as a new view.
    """
    if not article or not article.pk:
        return

    session_key = "viewed_suggested_article_ids"
    viewed_ids = request.session.get(session_key, [])
    article_key = str(article.pk)

    if article_key in viewed_ids:
        return

    SuggestedArticle.objects.filter(pk=article.pk).update(view_count=F("view_count") + 1)
    article.view_count = (article.view_count or 0) + 1

    viewed_ids.append(article_key)
    request.session[session_key] = viewed_ids[-1000:]
    request.session.modified = True

    log_activity(
        request,
        ActivityLog.EventType.ARTICLE_VIEWED,
        article=article,
        details={"view_count_after": article.view_count},
    )


def get_openkb_wiki_articles(sort_by_views=False):
    """Return public article cards from published Django articles only.

    Raw /wiki/*.md files are no longer treated as public pages. OpenKB still
    uses wiki/sources internally for AI indexing, but the website links to the
    safe Django article route instead of exposing Markdown file paths.
    """
    articles = []

    queryset = SuggestedArticle.objects.select_related("owner").filter(
        status=SuggestedArticle.Status.PUBLISHED,
    ).annotate(
        db_helpful_vote_count=Count(
            "votes",
            filter=Q(votes__value=ArticleVote.VoteValue.UP),
        )
    )

    for suggested in queryset:
        modified_at = timezone.localtime(suggested.updated_at).strftime("%Y-%m-%d %H:%M")
        articles.append({
            "title": suggested.title,
            "type": "Article",
            "date": modified_at,
            "views": suggested.view_count or 0,
            "likes": getattr(suggested, "db_helpful_vote_count", 0) or 0,
            "url": suggested.public_url,
            "path": "",
            "raw_markdown": build_article_markdown(suggested),
            "author": suggested.author_display,
            "keywords": suggested.keyword_list,
            "suggested_id": suggested.pk,
        })

    if sort_by_views:
        articles.sort(
            key=lambda item: (item.get("views") or 0, item.get("date") or ""),
            reverse=True,
        )
    else:
        articles.sort(key=lambda item: item["date"], reverse=True)
    return articles


def is_ldap_managed_user(user):
    """Return True only when the account is explicitly marked as AD-managed.

    Do not infer AD ownership from the username or email domain. A local Django
    user may legitimately use an email such as alice@openkb.local and should
    still be allowed to change their local password.
    """
    profile = getattr(user, "kb_profile", None)
    if not profile:
        return False

    if hasattr(profile, "AuthSource"):
        return profile.auth_source == profile.AuthSource.AD

    # Compatibility fallback for older databases/code during deployment.
    return bool(getattr(profile, "is_ldap_type", False))


def get_user_profile(user):
    if not user.is_authenticated:
        return None

    profile, created = UserProfile.objects.get_or_create(user=user)

    # Keep superusers and Admin Users role accounts visible as Admin unless already LDAP admin.
    # Article Manager accounts may also be staff for limited Django admin access,
    # so staff status alone must not promote someone to full Admin.
    try:
        has_admin_role = user.groups.filter(name="Admin Users").exists()
    except Exception:
        has_admin_role = False

    if (user.is_superuser or has_admin_role) and profile.account_type not in {
        UserProfile.AccountType.ADMIN,
        UserProfile.AccountType.LDAP_ADMIN,
    }:
        profile.account_type = (
            UserProfile.AccountType.LDAP_ADMIN
            if profile.auth_source == UserProfile.AuthSource.AD
            else UserProfile.AccountType.ADMIN
        )
        profile.save(update_fields=["account_type", "updated_at"])

    return profile


def user_can_access_main_site(user):
    if not user.is_authenticated or not user.is_active:
        return False

    if user_has_disabled_role(user):
        return False

    profile = get_user_profile(user)
    return bool(profile and profile.can_access_main_site)


def main_site_login_required(view_func):
    @wraps(view_func)
    @login_required
    def wrapper(request, *args, **kwargs):
        if not user_can_access_main_site(request.user):
            logout(request)
            return redirect("root_login")
        return view_func(request, *args, **kwargs)

    return wrapper


def get_account_type_display(user):
    profile = get_user_profile(user)
    if not profile:
        return "Guest"

    if profile.account_type == UserProfile.AccountType.LDAP_USER:
        return "Domain User"
    if profile.account_type == UserProfile.AccountType.LDAP_ADMIN:
        return "Domain Admin"
    if profile.account_type == UserProfile.AccountType.USER:
        return "Local User"
    if profile.account_type == UserProfile.AccountType.ADMIN:
        return "Local Admin"

    return profile.get_account_type_display()


def format_profile_display_name(user):
    full_name = user.get_full_name().strip()
    return full_name or user.get_username()


def paginate_articles(request, articles, per_page=20, page_param="page"):
    """Paginate article lists safely for the index/search page.

    page_param lets homepage tabs keep separate pagination states while the
    normal search page continues using the default ?page= parameter.
    """
    paginator = Paginator(articles, per_page)
    page_number = request.GET.get(page_param, 1)

    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    return page_obj


def get_profile_account_context(user):
    user_is_ldap_managed = is_ldap_managed_user(user)
    profile, created = UserProfile.objects.get_or_create(user=user)
    mfa_device = getattr(user, "kb_mfa_device", None)
    mfa_required = user_requires_mfa(user)

    return {
        "total_user_article_count": SuggestedArticle.objects.filter(owner=user).count(),
        "profile_display_name": format_profile_display_name(user),
        "user_is_ldap_managed": user_is_ldap_managed,
        "account_type_display": get_account_type_display(user),
        "auth_source_display": profile.get_auth_source_display() if hasattr(profile, "get_auth_source_display") else "Local user",
        "can_change_local_password": user.has_usable_password() and not user_is_ldap_managed,
        "can_confirm_profile_changes": user.has_usable_password(),
        "can_view_articles": user_can_view_articles(user),
        "can_add_articles": user_can_add_articles(user),
        "can_manage_articles": user_can_manage_articles(user),
        "can_use_admin_tools": user_can_use_admin_tools(user),
        "can_see_article_management": user_can_add_articles(user) or user_can_manage_articles(user),
        "role_permissions_summary": role_permissions_summary(user),
        "profile_preferred_language": profile.preferred_language,
        "supported_languages": settings.LANGUAGES,
        "mfa_required": mfa_required,
        "local_mfa_required": mfa_required,  # backwards-compatible template key
        "mfa_device": mfa_device,
        "mfa_enabled": bool(mfa_device and mfa_device.confirmed),
        "mfa_last_verified_at": getattr(mfa_device, "last_verified_at", None),
    }


def validate_profile_password_policy(password, user):
    """Return password policy issues for the profile change-password form.

    This enforces the local project policy used for Django-managed accounts:
    minimum length plus uppercase, lowercase, number, and special character.
    LDAP-managed users should change passwords through LDAP/AD instead.
    """
    issues = []

    if len(password) < 12:
        issues.append("Password must be at least 12 characters long.")
    if not re.search(r"[A-Z]", password):
        issues.append("Password must include at least 1 uppercase letter.")
    if not re.search(r"[a-z]", password):
        issues.append("Password must include at least 1 lowercase letter.")
    if not re.search(r"[0-9]", password):
        issues.append("Password must include at least 1 number.")
    if not re.search(r"[^A-Za-z0-9]", password):
        issues.append("Password must include at least 1 special character.")

    lower_password = password.lower()
    username = (user.get_username() or "").lower()
    email_name = (user.email or "").split("@")[0].lower()

    if username and len(username) >= 3 and username in lower_password:
        issues.append("Password must not contain your username.")
    if email_name and len(email_name) >= 3 and email_name in lower_password:
        issues.append("Password must not contain the name part of your email address.")

    return issues



def get_public_article_updated_at(article):
    """Return the timestamp that should be shown on the public article page.

    Hidden pending-update activity should not make the published article look
    updated before an admin approves it. For published articles, prefer the
    approval timestamp, then creation timestamp. For non-published owner/admin
    preview, fall back to updated_at.
    """
    if article is None:
        return None

    approved_at = getattr(article, "approved_at", None)
    created_at = getattr(article, "created_at", None)
    updated_at = getattr(article, "updated_at", None)

    if getattr(article, "status", None) == SuggestedArticle.Status.PUBLISHED:
        return approved_at or created_at or updated_at

    return updated_at or approved_at or created_at




# Administrative cleanup: larger service groups live in smaller modules.
# Re-export them here so existing imports from kb.views.services continue to work.
from .services_bulk import (  # noqa: F401
    BULK_EXPORT_PART_SIZE_BYTES,
    BULK_IMPORT_MAX_UPLOAD_BYTES,
    BULK_IMPORT_MAX_UNCOMPRESSED_BYTES,
    make_unique_article_filename,
    safe_zip_member_name,
    safe_uploaded_filename,
    make_unique_upload_filename,
    rewrite_uploaded_file_references,
    markdown_title_and_body,
    build_bulk_export_payload,
    _upload_file_size,
    _article_export_size_estimate,
    split_articles_for_bulk_export,
    build_single_bulk_export_zip,
    build_bulk_export_download,
    copy_imported_uploads_from_zip,
    import_articles_from_zip,
    get_article_image_cards,
    get_article_image_cards_from_filenames,
)
from .services_search import (  # noqa: F401
    tokenize_search_query,
    strip_markdown_for_search,
    build_search_excerpt,
    article_matches_title_or_keywords,
    search_public_articles_by_title_keywords,
    rank_articles_for_query,
    get_contextual_related_articles,
)
from .services_ai import (  # noqa: F401
    get_openkb_ai_model,
    scrub_openkb_runtime_log_files,
    ensure_openkb_config_model,
    OpenKBAIOverloaded,
    acquire_openkb_ai_slot,
    release_openkb_ai_slot,
    run_openkb_query,
    is_openkb_small_talk_request,
    build_openkb_small_talk_answer,
    is_openkb_article_recommendation_request,
    is_openkb_latest_article_request,
    normalize_openkb_article_query,
    find_related_openkb_articles,
    build_openkb_article_recommendation_answer,
    get_client_ip,
    log_activity,
    get_openkb_ai_rate_identifier,
    check_openkb_ai_rate_limit,
    clean_openkb_ai_answer,
    answer_indicates_no_openkb_match,
    should_show_openkb_related_articles,
    clean_openkb_ai_error_message,
    redact_openkb_debug_text,
    openkb_ai_output_indicates_error,
)
