import os
import io
import json
import logging
import re
import shutil
import subprocess
import sys
import time
import uuid
import zipfile
from datetime import datetime
from functools import wraps
from pathlib import Path

import bleach
import markdown
from PIL import Image, UnidentifiedImageError
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.views import LoginView
from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import F, Q
from django.http import FileResponse, Http404, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone, translation
from django.utils.translation import gettext as _
from django.utils.http import url_has_allowed_host_and_scheme
from django.views.decorators.http import require_POST

from ..models import ArticleImageUploadLog, ArticleVote, SuggestedArticle, UserProfile, SiteSetting, UserMFADevice, normalize_article_title
from ..mfa import user_requires_mfa


IGNORED_WIKI_NAMES = {"AGENTS.md", "log.md", "index.md", "README.md"}
DJANGO_ARTICLE_SOURCE_MARKER = "generated_by: django-suggested-article"

# Small image files that users paste/upload into suggested Markdown articles.
# These are served through the protected /wiki/uploads/<filename> view, not by
# exposing the uploads directory directly.
ALLOWED_ARTICLE_IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif", ".webp"}
ALLOWED_ARTICLE_IMAGE_FORMATS = {
    "PNG": {"extension": ".png", "content_type": "image/png"},
    "JPEG": {"extension": ".jpg", "content_type": "image/jpeg"},
    "JPG": {"extension": ".jpg", "content_type": "image/jpeg"},
    "GIF": {"extension": ".gif", "content_type": "image/gif"},
    "WEBP": {"extension": ".webp", "content_type": "image/webp"},
}
MAX_ARTICLE_IMAGE_SIZE_BYTES = 2 * 1024 * 1024
MAX_ARTICLE_IMAGE_PIXELS = 16_000_000
ARTICLE_IMAGE_RE = re.compile(r"!\[[^\]]*\]\(/wiki/uploads/([^)/?#]+)(?:[?#][^)]*)?\)")

logger = logging.getLogger(__name__)


def remove_openkb_internal_metadata(markdown_text):
    """Remove Django/OpenKB sync metadata before public display/search/AI snippets.

    The Markdown source files keep small internal markers so Django can reconcile
    generated files, but those markers should never appear in search results,
    article snippets, or OpenKB AI responses. This also handles already-flattened
    variants such as "!generated by: django suggested article; article id: ...".
    """
    text = markdown_text or ""

    # Remove the original hidden marker comment.
    text = re.sub(
        r"^\s*<!--\s*generated[_\s-]*by\s*:\s*django[-_\s]*suggested[-_\s]*article[^>]*-->\s*",
        "",
        text,
        flags=re.IGNORECASE | re.MULTILINE,
    )

    # Remove any leaked/plain-text version of that marker from search/AI output.
    text = re.sub(
        r"^\s*!?\s*generated[_\s-]*by\s*:\s*django[-_\s]*suggested[-_\s]*article\s*;?\s*article[_\s-]*id\s*:\s*[^\r\n]+\s*",
        "",
        text,
        flags=re.IGNORECASE | re.MULTILINE,
    )

    # Remove generated sync front matter from OpenKB summaries if it is ever
    # shown directly. Keep normal user-written front matter untouched.
    text = re.sub(
        r"^---\s*\n(?=[\s\S]*?generated[_\s-]*by\s*:\s*django-openkb-sync)(?:.|\n)*?---\s*\n?",
        "",
        text,
        flags=re.IGNORECASE,
    )

    return text.lstrip("\ufeff\n\r ")


SEARCH_STOPWORDS = {
    "a", "an", "and", "are", "as", "at", "be", "by", "can", "do", "does",
    "for", "from", "how", "i", "in", "is", "it", "me", "my", "of", "on",
    "or", "our", "the", "this", "to", "was", "we", "what", "when", "where",
    "which", "who", "why", "with", "you", "your",
    # Chat filler / greetings should not make Ask OpenKB AI recommend random
    # articles just because words like "there" appear in article bodies.
    "hi", "hello", "hey", "there", "still", "alive", "thanks", "thank",
    "please", "pls", "ok", "okay", "yo",
}


def slugify_title(title):
    slug = title.strip().lower()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    slug = slug.strip("-")
    return slug or "untitled"


def find_duplicate_article_by_title(title, exclude_pk=None):
    """Return an existing article with the same normalized title, if any."""
    normalized_title = normalize_article_title(title)
    if not normalized_title:
        return None

    queryset = SuggestedArticle.objects.all()
    if exclude_pk:
        queryset = queryset.exclude(pk=exclude_pk)

    for article in queryset.only("id", "title"):
        if normalize_article_title(article.title) == normalized_title:
            return article
    return None


def duplicate_title_error_message(title):
    return _("An article with the title ‘%(title)s’ already exists. Please use a different title.") % {"title": title}


def get_review_notes_history(article):
    """Return review-note history newest first for templates."""
    history = article.review_notes_history or []
    if not isinstance(history, list):
        return []
    return list(reversed(history))


def get_safe_return_url(request, fallback_view_name="edit_my_suggestions"):
    """Return a safe local URL for edit/delete flows.

    This lets the same article edit/delete views send users back to the page
    they came from, such as Manage pending articles for admins or Edit my
    articles for owners, without allowing open redirects.
    """
    candidate = (request.POST.get("next") or request.GET.get("next") or "").strip()
    if candidate and url_has_allowed_host_and_scheme(
        candidate,
        allowed_hosts={request.get_host()},
        require_https=request.is_secure(),
    ):
        return candidate
    return reverse(fallback_view_name)


def user_is_site_admin(user):
    """Return True only for explicitly trusted DjOpenKB admins.

    Staff status alone is not enough for profile-level admin tools. A user must
    be a superuser or have a UserProfile account type of Admin / LDAP admin.
    """
    if not getattr(user, "is_authenticated", False) or not user.is_active:
        return False

    if user.is_superuser:
        return True

    profile = getattr(user, "kb_profile", None)
    return bool(profile and profile.is_admin_type)


def user_can_manage_article(user, article):
    """Return True when a user can edit/delete an article they do not own."""
    return bool(article and (article.owner == user or user_is_site_admin(user)))


def init_openkb_storage():
    settings.OPENKB_DATA_DIR.mkdir(parents=True, exist_ok=True)
    settings.OPENKB_RAW_DIR.mkdir(parents=True, exist_ok=True)
    settings.OPENKB_WIKI_DIR.mkdir(parents=True, exist_ok=True)
    (settings.OPENKB_WIKI_DIR / "sources").mkdir(parents=True, exist_ok=True)
    (settings.OPENKB_WIKI_DIR / "summaries").mkdir(parents=True, exist_ok=True)
    (settings.OPENKB_WIKI_DIR / "concepts").mkdir(parents=True, exist_ok=True)

    index_file = settings.OPENKB_WIKI_DIR / "index.md"
    if not index_file.exists():
        index_file.write_text(
            "# Knowledge Base Index\n\n"
            "## Documents\n\n"
            "## Concepts\n\n"
            "## Explorations\n",
            encoding="utf-8",
        )


def get_openkb_uploads_dir():
    """Folder used for small images pasted into suggested Markdown articles."""
    upload_dir = settings.OPENKB_WIKI_DIR / "uploads"
    upload_dir.mkdir(parents=True, exist_ok=True)
    return upload_dir


def validate_article_image_upload(uploaded_file):
    """Return image metadata when an uploaded file is a safe supported image.

    Browser-reported content_type can be faked, so this verifies the actual file
    bytes with Pillow and only accepts PNG, JPG/JPEG, GIF, and WEBP.
    """
    original_suffix = Path(uploaded_file.name or "").suffix.lower()
    if original_suffix and original_suffix not in ALLOWED_ARTICLE_IMAGE_EXTENSIONS:
        raise ValidationError("Only PNG, JPG, GIF, or WEBP images are allowed.")

    if uploaded_file.size > MAX_ARTICLE_IMAGE_SIZE_BYTES:
        raise ValidationError("Image is too large. Maximum allowed size is 2 MB.")

    try:
        uploaded_file.seek(0)
        with Image.open(uploaded_file) as image:
            image.verify()
            detected_format = (image.format or "").upper()
            width, height = image.size
    except (UnidentifiedImageError, OSError, ValueError):
        raise ValidationError("The uploaded file is not a valid image.")
    finally:
        try:
            uploaded_file.seek(0)
        except Exception:
            pass

    image_info = ALLOWED_ARTICLE_IMAGE_FORMATS.get(detected_format)
    if not image_info:
        raise ValidationError("Only PNG, JPG, GIF, or WEBP images are allowed.")

    if width * height > MAX_ARTICLE_IMAGE_PIXELS:
        raise ValidationError("Image dimensions are too large. Please upload a smaller image.")

    return {
        "format": detected_format,
        "extension": image_info["extension"],
        "content_type": image_info["content_type"],
        "width": width,
        "height": height,
    }


def is_allowed_article_image_filename(filename):
    """Return True only for server-managed image filenames."""
    safe_name = safe_uploaded_filename(filename)
    if not safe_name or safe_name != filename:
        return False
    return Path(safe_name).suffix.lower() in ALLOWED_ARTICLE_IMAGE_EXTENSIONS


def uploaded_image_content_type(filename):
    suffix = Path(filename or "").suffix.lower()
    if suffix in {".jpg", ".jpeg"}:
        return "image/jpeg"
    if suffix == ".png":
        return "image/png"
    if suffix == ".gif":
        return "image/gif"
    if suffix == ".webp":
        return "image/webp"
    return "application/octet-stream"


def extract_article_image_filenames(markdown_text):
    """Return unique uploaded image filenames referenced in Markdown body."""
    seen = []
    for filename in ARTICLE_IMAGE_RE.findall(markdown_text or ""):
        if filename not in seen and "/" not in filename and "\\" not in filename:
            seen.append(filename)
    return seen


def article_image_markdown(filename):
    return f"![image](/wiki/uploads/{filename})"


def article_image_url(filename):
    return f"/wiki/uploads/{filename}"


def delete_uploaded_image_file(filename):
    if not filename or "/" in filename or "\\" in filename or filename in {".", ".."}:
        return

    upload_dir = get_openkb_uploads_dir().resolve()
    file_path = (upload_dir / filename).resolve()

    if str(file_path).startswith(str(upload_dir)) and file_path.exists() and file_path.is_file():
        file_path.unlink()


def image_is_used_by_other_article(filename, current_article=None):
    queryset = SuggestedArticle.objects.all()
    if current_article and current_article.pk:
        queryset = queryset.exclude(pk=current_article.pk)

    for article in queryset.only("body", "image_assets"):
        if filename in (article.image_assets or []):
            return True
        if filename in extract_article_image_filenames(article.body):
            return True
    return False


def sync_article_image_assets(article, old_assets=None):
    """Tie currently referenced uploaded images to this article and clean stale ones."""
    old_assets = set(old_assets if old_assets is not None else (article.image_assets or []))
    new_assets = set(extract_article_image_filenames(article.body))

    stale_assets = old_assets - new_assets
    for filename in stale_assets:
        if not image_is_used_by_other_article(filename, current_article=article):
            delete_uploaded_image_file(filename)

    article.image_assets = sorted(new_assets)
    SuggestedArticle.objects.filter(pk=article.pk).update(image_assets=article.image_assets)
    return article.image_assets


def clear_committed_pending_uploads(request, image_assets):
    pending_uploads = request.session.get("pending_article_uploads", [])
    if not pending_uploads:
        return

    image_assets = set(image_assets or [])
    request.session["pending_article_uploads"] = [
        item for item in pending_uploads if item not in image_assets
    ]
    request.session.modified = True


def user_can_use_admin_tools(user):
    """Return True for users allowed to use profile-level admin maintenance tools."""
    return user_is_site_admin(user)


def admin_tools_required(view_func):
    """Require normal site access plus explicit DjOpenKB admin permission.

    Anonymous users are still redirected to login by main_site_login_required.
    Logged-in non-admin users receive 404 so admin-tool route discovery is less
    useful to scanners such as Gobuster.
    """
    @wraps(view_func)
    @main_site_login_required
    def wrapper(request, *args, **kwargs):
        if not user_can_use_admin_tools(request.user):
            raise Http404("Page not found")
        return view_func(request, *args, **kwargs)

    return wrapper


def extract_uploaded_file_filenames_from_text(text):
    """Find /wiki/uploads/<filename> references from Markdown or rendered HTML text."""
    if not text:
        return set()

    filenames = set(extract_article_image_filenames(text))

    # Also catch HTML img src or plain pasted URLs such as:
    # /wiki/uploads/example.png, http://host/wiki/uploads/example.png
    for filename in re.findall(r"/wiki/uploads/([A-Za-z0-9._-]+)", text):
        if filename and "/" not in filename and "\\" not in filename:
            filenames.add(filename)

    return filenames


def get_all_referenced_uploaded_files():
    """Return uploaded filenames still referenced by articles or Markdown files."""
    referenced = set()

    # 1) Trust Django article records first. This covers draft/published articles
    # and images tracked in image_assets.
    for article in SuggestedArticle.objects.only("body", "image_assets"):
        referenced.update(article.image_assets or [])
        referenced.update(extract_uploaded_file_filenames_from_text(article.body))

    # 2) Also scan all OpenKB wiki Markdown files. This protects manually added
    # Markdown files or files edited outside Django.
    wiki_dir = settings.OPENKB_WIKI_DIR
    if wiki_dir.exists():
        for markdown_file in wiki_dir.rglob("*.md"):
            try:
                text = markdown_file.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            referenced.update(extract_uploaded_file_filenames_from_text(text))

    return {
        filename for filename in referenced
        if filename and "/" not in filename and "\\" not in filename
    }


def get_stray_upload_cleanup_min_age_minutes():
    """Return cleanup age threshold from Django Admin site settings."""
    try:
        value = SiteSetting.load().stray_upload_cleanup_min_age_minutes
    except Exception:
        value = 1440

    try:
        value = int(value)
    except (TypeError, ValueError):
        value = 1440

    return max(value, 0)



def get_article_image_upload_log(filename):
    """Return the upload audit row for a generated article image filename."""
    filename = safe_uploaded_filename(filename)
    if not filename:
        return None

    try:
        return ArticleImageUploadLog.objects.select_related("uploaded_by", "deleted_by").filter(filename=filename).first()
    except Exception:
        logger.exception("Unable to read article image upload log for %s", filename)
        return None


def mark_article_image_deleted(filename, actor=None, reason=""):
    """Best-effort audit update when an uploaded article image is deleted."""
    filename = safe_uploaded_filename(filename)
    if not filename:
        return

    try:
        ArticleImageUploadLog.objects.filter(filename=filename, deleted_at__isnull=True).update(
            deleted_at=timezone.now(),
            deleted_by=actor if getattr(actor, "pk", None) else None,
            delete_reason=reason or "",
        )
    except Exception:
        logger.exception("Unable to mark article image upload log as deleted for %s", filename)

def find_stray_uploaded_files(min_age_minutes=1440):
    """Return uploaded files that are not referenced anywhere.

    The minimum age protects someone who is currently editing an article: a
    file uploaded seconds ago may not be saved into Markdown yet.
    """
    init_openkb_storage()
    upload_dir = get_openkb_uploads_dir().resolve()
    referenced = get_all_referenced_uploaded_files()
    cutoff_time = timezone.now().timestamp() - (min_age_minutes * 60)

    stray_files = []

    if not upload_dir.exists():
        return stray_files

    for file_path in upload_dir.iterdir():
        if not file_path.is_file():
            continue

        filename = file_path.name
        if filename in referenced:
            continue

        try:
            stat = file_path.stat()
        except OSError:
            continue

        if stat.st_mtime > cutoff_time:
            continue

        extension = file_path.suffix.lower().lstrip(".") or "(no extension)"
        is_previewable_image = file_path.suffix.lower() in {".png", ".jpg", ".jpeg", ".gif", ".webp"}

        upload_log = get_article_image_upload_log(filename)
        uploader_display = ""
        uploader_email = ""
        uploader_account_type = ""
        uploaded_at = None

        if upload_log:
            uploader_display = upload_log.uploader_display
            uploader_email = upload_log.uploader_email_snapshot
            uploader_account_type = upload_log.uploader_account_type_snapshot
            uploaded_at = upload_log.uploaded_at

        stray_files.append({
            "filename": filename,
            "url": article_image_url(filename),
            "extension": extension,
            "is_previewable_image": is_previewable_image,
            "size_bytes": stat.st_size,
            "size_kb": round(stat.st_size / 1024, 1),
            "modified_at": datetime.fromtimestamp(stat.st_mtime),
            "path": file_path,
            "upload_log": upload_log,
            "uploader_display": uploader_display,
            "uploader_email": uploader_email,
            "uploader_account_type": uploader_account_type,
            "uploaded_at": uploaded_at,
        })
    stray_files.sort(key=lambda item: item["modified_at"], reverse=True)
    return stray_files


def make_unique_article_filename(title, original_filename=""):
    """Create a unique Markdown filename for an imported article."""
    timestamp_slug = timezone.localtime(timezone.now()).strftime("%Y%m%d-%H%M%S")
    original_name = Path(original_filename or "").name
    original_stem = Path(original_name).stem if original_name else ""
    base_slug = slugify_title(title or original_stem or "imported-article")
    candidate = f"{timestamp_slug}-{base_slug}.md"

    while SuggestedArticle.objects.filter(filename=candidate).exists():
        candidate = f"{timestamp_slug}-{base_slug}-{uuid.uuid4().hex[:6]}.md"

    return candidate


def safe_zip_member_name(name):
    """Return a normalized zip member name, or empty string for unsafe paths."""
    normalized = str(name or "").replace("\\", "/").lstrip("/")
    parts = [part for part in normalized.split("/") if part not in {"", "."}]

    if not parts or any(part == ".." for part in parts):
        return ""

    return "/".join(parts)


def safe_uploaded_filename(name):
    """Keep only the filename portion and strip path traversal characters."""
    filename = Path(str(name or "").replace("\\", "/")).name.strip()
    if not filename or filename in {".", ".."}:
        return ""
    return filename


def make_unique_upload_filename(original_filename):
    """Create a non-conflicting filename under openkb-data/wiki/uploads."""
    upload_dir = get_openkb_uploads_dir()
    original = safe_uploaded_filename(original_filename)
    suffix = Path(original).suffix.lower()
    stem = slugify_title(Path(original).stem or "uploaded-file")
    timestamp = timezone.localtime(timezone.now()).strftime("%Y%m%d-%H%M%S")

    candidate = f"{timestamp}-{uuid.uuid4().hex[:8]}-{stem}{suffix}"
    while (upload_dir / candidate).exists():
        candidate = f"{timestamp}-{uuid.uuid4().hex[:12]}-{stem}{suffix}"

    return candidate


def rewrite_uploaded_file_references(text, filename_map):
    """Rewrite /wiki/uploads/<old> references after imported files are renamed."""
    updated = text or ""
    for old_name, new_name in filename_map.items():
        if not old_name or not new_name or old_name == new_name:
            continue
        updated = updated.replace(f"/wiki/uploads/{old_name}", f"/wiki/uploads/{new_name}")
        updated = updated.replace(f"uploads/{old_name}", f"uploads/{new_name}")
    return updated


def markdown_title_and_body(markdown_text, fallback_title="Imported article"):
    """Parse a title/body from Markdown when importing a zip without manifest.json."""
    text = (markdown_text or "").lstrip("\ufeff")
    lines = text.splitlines()
    title = fallback_title

    if lines and lines[0].startswith("# "):
        title = lines[0][2:].strip() or fallback_title
        lines = lines[1:]
        if lines and not lines[0].strip():
            lines = lines[1:]

    body = "\n".join(lines).strip()

    keyword_match = re.search(r"\n?\*\*Keywords:\*\*\s*(.+?)\s*$", body, flags=re.IGNORECASE | re.DOTALL)
    keywords = ""
    if keyword_match:
        keywords = keyword_match.group(1).strip()
        body = body[:keyword_match.start()].rstrip()

    return title, body, keywords


def build_bulk_export_payload():
    """Build the JSON manifest and file list for article bulk export."""
    articles = []
    referenced_uploads = set()

    for article in SuggestedArticle.objects.select_related("owner").order_by("created_at", "id"):
        image_assets = sorted(set((article.image_assets or []) + extract_article_image_filenames(article.body)))
        referenced_uploads.update(image_assets)

        articles.append({
            "title": article.title,
            "body": article.body,
            "keywords": article.keywords,
            "status": article.status,
            "filename": article.filename,
            "raw_path": article.raw_path,
            "wiki_path": article.wiki_path,
            "image_assets": image_assets,
            "created_at": article.created_at.isoformat() if article.created_at else "",
            "updated_at": article.updated_at.isoformat() if article.updated_at else "",
            "author_username": article.author_username,
            "author_email": article.author_email,
        })

    return {
        "format": "djopenkb-bulk-export-v1",
        "exported_at": timezone.now().isoformat(),
        "article_count": len(articles),
        "articles": articles,
        "uploads": sorted(referenced_uploads),
    }


def copy_imported_uploads_from_zip(zip_file, upload_member_names):
    """Copy uploaded files from an import zip into openkb-data/wiki/uploads.

    Returns a mapping of original filename -> new filename so article bodies can
    be rewritten safely when a filename already exists.
    """
    upload_dir = get_openkb_uploads_dir()
    filename_map = {}

    for member_name in upload_member_names:
        safe_member = safe_zip_member_name(member_name)
        if not safe_member:
            continue

        original_filename = safe_uploaded_filename(safe_member)
        if not original_filename:
            continue

        new_filename = make_unique_upload_filename(original_filename)
        target_path = (upload_dir / new_filename).resolve()

        try:
            target_path.relative_to(upload_dir.resolve())
        except ValueError:
            continue

        if Path(original_filename).suffix.lower() not in ALLOWED_ARTICLE_IMAGE_EXTENSIONS:
            continue

        with zip_file.open(member_name, "r") as source:
            data = source.read(MAX_ARTICLE_IMAGE_SIZE_BYTES + 1)

        if len(data) > MAX_ARTICLE_IMAGE_SIZE_BYTES:
            continue

        from django.core.files.uploadedfile import SimpleUploadedFile
        temp_upload = SimpleUploadedFile(original_filename, data)

        try:
            image_info = validate_article_image_upload(temp_upload)
        except ValidationError:
            continue

        # Rename using the verified image type rather than trusting the zip filename.
        new_filename = make_unique_upload_filename(Path(original_filename).with_suffix(image_info["extension"]).name)
        target_path = (upload_dir / new_filename).resolve()
        try:
            target_path.relative_to(upload_dir.resolve())
        except ValueError:
            continue

        target_path.write_bytes(data)
        filename_map[original_filename] = new_filename

    return filename_map


def import_articles_from_zip(uploaded_zip, owner):
    """Import articles and uploaded files from a DjOpenKB bulk export zip.

    All imported articles are assigned to the admin user performing the import.
    """
    imported_count = 0
    errors = []

    with zipfile.ZipFile(uploaded_zip) as archive:
        members = [item for item in archive.infolist() if not item.is_dir()]
        safe_names = {safe_zip_member_name(item.filename): item.filename for item in members if safe_zip_member_name(item.filename)}

        # Hard safety limits for admin imports.
        total_uncompressed = sum(item.file_size for item in members)
        if total_uncompressed > 200 * 1024 * 1024:
            raise ValueError("Import zip is too large after extraction. Maximum allowed uncompressed size is 200 MB.")

        upload_members = [
            original_name for safe_name, original_name in safe_names.items()
            if safe_name.startswith("uploads/")
        ]
        filename_map = copy_imported_uploads_from_zip(archive, upload_members)

        manifest_name = safe_names.get("manifest.json")
        manifest = None
        if manifest_name:
            with archive.open(manifest_name, "r") as manifest_file:
                manifest = json.loads(manifest_file.read().decode("utf-8"))

        article_payloads = []

        if manifest and manifest.get("format") == "djopenkb-bulk-export-v1":
            for item in manifest.get("articles", []):
                article_payloads.append({
                    "title": item.get("title") or "Imported article",
                    "body": item.get("body") or "",
                    "keywords": item.get("keywords") or "",
                    "status": item.get("status") or SuggestedArticle.Status.PUBLISHED,
                    "filename": item.get("filename") or "",
                })
        else:
            markdown_names = [
                original_name for safe_name, original_name in safe_names.items()
                if safe_name.lower().endswith(".md") and not safe_name.startswith("uploads/")
            ]

            for markdown_name in markdown_names:
                safe_name = safe_zip_member_name(markdown_name)
                with archive.open(markdown_name, "r") as markdown_file:
                    markdown_text = markdown_file.read().decode("utf-8", errors="ignore")

                title, body, keywords = markdown_title_and_body(
                    markdown_text,
                    fallback_title=Path(safe_name).stem.replace("-", " ").replace("_", " ").title(),
                )
                article_payloads.append({
                    "title": title,
                    "body": body,
                    "keywords": keywords,
                    "status": SuggestedArticle.Status.PUBLISHED,
                    "filename": Path(safe_name).name,
                })

        if not article_payloads:
            raise ValueError("No articles found in the zip. Include manifest.json or Markdown files.")

        seen_import_titles = set()

        for item in article_payloads:
            title = (item.get("title") or "Imported article").strip()[:200]
            body = rewrite_uploaded_file_references(item.get("body") or "", filename_map)
            keywords = (item.get("keywords") or "").strip()[:500]
            status = item.get("status") or SuggestedArticle.Status.PUBLISHED

            if status not in dict(SuggestedArticle.Status.choices):
                status = SuggestedArticle.Status.PUBLISHED

            normalized_title = normalize_article_title(title)
            if normalized_title in seen_import_titles:
                errors.append(f"Skipped duplicate title inside import zip: {title}")
                continue
            seen_import_titles.add(normalized_title)

            duplicate_article = find_duplicate_article_by_title(title)
            if duplicate_article:
                errors.append(f"Skipped duplicate title already in OpenKB: {title}")
                continue

            filename = make_unique_article_filename(title, item.get("filename") or "")

            try:
                article = SuggestedArticle.objects.create(
                    owner=owner,
                    title=title,
                    body=body,
                    keywords=keywords,
                    filename=filename,
                    wiki_path=f"sources/{filename}",
                    raw_path=f"raw/{filename}",
                    status=status,
                    image_assets=extract_article_image_filenames(body),
                )
                write_article_files(article)
                sync_article_image_assets(article, old_assets=[])
                imported_count += 1
            except Exception as error:
                errors.append(f"{title}: {error}")

    return imported_count, errors


def get_article_image_cards(article):
    return [
        {
            "filename": filename,
            "url": article_image_url(filename),
            "markdown": article_image_markdown(filename),
            "existing": True,
        }
        for filename in (article.image_assets or extract_article_image_filenames(article.body))
    ]


def clean_wiki_title(file_path):
    return file_path.stem.replace("-", " ").replace("_", " ").title()


def format_user_for_markdown(user):
    full_name = user.get_full_name().strip()
    if full_name and user.email:
        return f"{full_name} ({user.email})"
    if user.email:
        return user.email
    return user.get_username()


def build_article_markdown(article):
    keyword_line = ""
    if article.keywords:
        keyword_line = f"\n\n**Keywords:** {article.keywords}"

    article_id = getattr(article, "id", "") or "export"
    return (
        f"<!-- {DJANGO_ARTICLE_SOURCE_MARKER}; article_id: {article_id} -->\n"
        f"# {article.title}\n\n"
        f"{article.body}\n"
        f"{keyword_line}\n"
    )


def plain_markdown_excerpt(markdown_text, max_length=260):
    """Create a short plain-text summary from Markdown for the OpenKB AI index."""
    text = remove_openkb_internal_metadata(markdown_text)

    # Remove YAML front matter, HTML comments, images, links, and common Markdown symbols.
    text = re.sub(r"^---.*?---", " ", text, flags=re.DOTALL).strip()
    text = re.sub(r"<!--.*?-->", " ", text, flags=re.DOTALL)
    text = re.sub(r"!\[[^\]]*\]\([^)]+\)", " ", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"\*\*Keywords:\*\*\s*.*", " ", text, flags=re.IGNORECASE)
    text = re.sub(r"[#>*_`~|\-]+", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    if not text:
        return "Django published OpenKB article."

    if len(text) > max_length:
        text = text[:max_length].rsplit(" ", 1)[0].rstrip() + "..."

    return text


def extract_markdown_title(file_path, raw_markdown):
    """Use the first Markdown H1 as the AI title, otherwise fallback to filename."""
    for line in (raw_markdown or "").splitlines():
        line = line.strip()
        if line.startswith("# "):
            return line[2:].strip() or clean_wiki_title(file_path)
    return clean_wiki_title(file_path)


def extract_index_section(existing_text, heading):
    """Preserve non-Django OpenKB sections when rebuilding index.md."""
    lines = existing_text.splitlines()
    start = None

    for index, line in enumerate(lines):
        if line.strip() == heading:
            start = index + 1
            break

    if start is None:
        return ""

    end = len(lines)
    for index in range(start, len(lines)):
        if lines[index].startswith("## "):
            end = index
            break

    return "\n".join(lines[start:end]).strip()


def ensure_article_filename(article):
    """Ensure every SuggestedArticle has a stable Markdown filename."""
    if article.filename:
        return article.filename

    timestamp_slug = timezone.localtime(article.created_at or timezone.now()).strftime("%Y%m%d-%H%M%S")
    base_slug = slugify_title(article.title)
    candidate = f"{timestamp_slug}-{base_slug}.md"
    counter = 2
    while SuggestedArticle.objects.filter(filename=candidate).exclude(pk=article.pk).exists():
        candidate = f"{timestamp_slug}-{base_slug}-{counter}.md"
        counter += 1

    article.filename = candidate
    return article.filename


def source_file_is_django_managed(path):
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")[:500]
    except OSError:
        return False
    return DJANGO_ARTICLE_SOURCE_MARKER in text


def reconcile_openkb_article_files():
    """Reconcile OpenKB files from the Django database as the source of truth.

    - Every Django article gets a raw Markdown file.
    - Only published Django articles get a public wiki/sources file.
    - Unpublished Django articles have their source file removed.
    - Old source files generated by this Django integration are removed when the
      database article no longer exists. Manually-created OpenKB source files are
      left untouched.
    """
    init_openkb_storage()

    sources_dir = settings.OPENKB_WIKI_DIR / "sources"
    managed_filenames = set()

    for article in SuggestedArticle.objects.all().order_by("id"):
        ensure_article_filename(article)
        write_article_files(article, sync_ai=False, mark_ai_stale=False)
        managed_filenames.add(article.filename)

    for source_path in sources_dir.glob("*.md"):
        if source_path.name in managed_filenames or source_path.name in IGNORED_WIKI_NAMES:
            continue
        if source_file_is_django_managed(source_path):
            try:
                source_path.unlink()
            except OSError as error:
                logger.warning("Could not remove stale Django OpenKB source %s: %s", source_path, error)


def write_openkb_django_sync_state(documents):
    """Write a small audit file so OpenKB/Django sync state can be inspected."""
    state_dir = settings.OPENKB_DATA_DIR / ".openkb"
    state_dir.mkdir(parents=True, exist_ok=True)
    state = {
        "generated_by": "django-openkb-sync",
        "synced_at": timezone.localtime(timezone.now()).isoformat(),
        "published_document_count": len(documents),
        "documents": documents,
    }
    (state_dir / "django_sync_state.json").write_text(
        json.dumps(state, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def get_openkb_ai_sync_state_path():
    """Return the lightweight state file used to decide whether AI sync is needed."""
    state_dir = settings.OPENKB_DATA_DIR / ".openkb"
    state_dir.mkdir(parents=True, exist_ok=True)
    return state_dir / "django_ai_sync_state.json"


def write_openkb_ai_sync_state(stale, reason, extra=None):
    """Persist whether Ask OpenKB AI needs a fresh Django/OpenKB sync."""
    init_openkb_storage()
    now_iso = timezone.localtime(timezone.now()).isoformat()
    state = {
        "generated_by": "django-openkb-ai-sync-state",
        "stale": bool(stale),
        "reason": reason,
        "updated_at": now_iso,
    }

    existing = read_openkb_ai_sync_state(default={})
    if stale:
        state["stale_since"] = existing.get("stale_since") or now_iso
        if existing.get("last_synced_at"):
            state["last_synced_at"] = existing.get("last_synced_at")
    else:
        state["last_synced_at"] = now_iso

    if extra:
        state.update(extra)

    get_openkb_ai_sync_state_path().write_text(
        json.dumps(state, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    return state


def read_openkb_ai_sync_state(default=None):
    """Read the on-demand AI sync state file."""
    path = get_openkb_ai_sync_state_path()
    if not path.exists():
        return default if default is not None else {"stale": True, "reason": "No AI sync state found."}

    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return default if default is not None else {"stale": True, "reason": "AI sync state could not be read."}


def mark_openkb_ai_stale(reason="Article content changed."):
    """Mark OpenKB AI index as needing a rebuild later.

    This is intentionally cheap and is used during article create/edit/publish/delete
    flows so admin redirects stay fast. The actual full sync happens only when
    someone asks OpenKB AI or when the management command is run manually.
    """
    try:
        write_openkb_ai_sync_state(True, reason)
    except Exception as error:
        logger.warning("Could not mark OpenKB AI sync state as stale: %s", error)


def openkb_ai_sync_is_stale():
    """Return True when the AI index should be rebuilt before answering."""
    state = read_openkb_ai_sync_state()
    if state.get("stale", True):
        return True

    wiki_dir = settings.OPENKB_WIKI_DIR
    index_file = wiki_dir / "index.md"
    summaries_dir = wiki_dir / "summaries"
    if not index_file.exists() or not summaries_dir.exists():
        return True

    return False


def ensure_openkb_ai_synced():
    """Synchronize OpenKB AI files only when article changes made them stale."""
    if openkb_ai_sync_is_stale():
        logger.info("OpenKB AI index is stale; syncing on demand before answering.")
        sync_openkb_ai_index()
    else:
        logger.info("OpenKB AI index is fresh; skipping sync before answering.")


def sync_openkb_ai_index():
    """Make Ask OpenKB AI aware of Django-published source articles.

    OpenKB query starts from wiki/index.md and wiki/summaries/*.md.
    Django writes published articles directly into wiki/sources/*.md, so this
    function creates lightweight summaries and rebuilds index.md from sources.
    No LLM call is made here, so it is safe to run before each AI query.
    """
    init_openkb_storage()
    reconcile_openkb_article_files()

    wiki_dir = settings.OPENKB_WIKI_DIR
    sources_dir = wiki_dir / "sources"
    summaries_dir = wiki_dir / "summaries"
    index_file = wiki_dir / "index.md"

    sources_dir.mkdir(parents=True, exist_ok=True)
    summaries_dir.mkdir(parents=True, exist_ok=True)

    existing_index = ""
    if index_file.exists():
        existing_index = index_file.read_text(encoding="utf-8", errors="ignore")

    existing_concepts = extract_index_section(existing_index, "## Concepts")
    existing_explorations = extract_index_section(existing_index, "## Explorations")

    # Remove old Django-generated summaries so deleted/unpublished articles vanish
    # from AI results. Keep any non-generated summaries that may exist.
    for summary_file in summaries_dir.glob("*.md"):
        try:
            text = summary_file.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if "generated_by: django-openkb-sync" in text:
            try:
                summary_file.unlink()
            except OSError:
                pass

    documents = []

    for source_path in sorted(sources_dir.rglob("*.md")):
        if source_path.name in IGNORED_WIKI_NAMES:
            continue

        try:
            raw_markdown = source_path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue

        relative_source = source_path.relative_to(wiki_dir).as_posix()
        doc_name = source_path.stem
        summary_relative = f"summaries/{doc_name}"
        title = extract_markdown_title(source_path, raw_markdown)
        brief = plain_markdown_excerpt(raw_markdown)

        summary_text = (
            "---\n"
            "doc_type: short\n"
            "generated_by: django-openkb-sync\n"
            f"full_text: {relative_source}\n"
            "---\n\n"
            f"# {title}\n\n"
            f"{brief}\n"
        )

        (summaries_dir / f"{doc_name}.md").write_text(summary_text, encoding="utf-8")

        documents.append({
            "source_relative": relative_source,
            "summary_relative": f"{summary_relative}.md",
            "title": title,
            "brief": brief,
            "django_managed": DJANGO_ARTICLE_SOURCE_MARKER in raw_markdown,
        })

    index_lines = [
        "# Knowledge Base Index",
        "",
        "## Documents",
    ]

    if documents:
        for item in documents:
            index_lines.append(
                f"- [[{item['summary_relative'].removesuffix('.md')}]] (short) — {item['title']}: {item['brief']}"
            )
    else:
        index_lines.append("")

    index_lines.extend(["", "## Concepts"])
    if existing_concepts:
        index_lines.extend(existing_concepts.splitlines())
    else:
        index_lines.append("")

    index_lines.extend(["", "## Explorations"])
    if existing_explorations:
        index_lines.extend(existing_explorations.splitlines())
    else:
        index_lines.append("")

    index_file.write_text("\n".join(index_lines).rstrip() + "\n", encoding="utf-8")
    write_openkb_django_sync_state(documents)
    write_openkb_ai_sync_state(
        False,
        "OpenKB AI index synced.",
        {"published_document_count": len(documents)},
    )


def prepare_article_display_markdown(raw_markdown, title, suggested=None):
    """Remove Django-generated wrapper Markdown from public article display.

    SuggestedArticle files are saved with a leading H1 title and a trailing
    **Keywords:** metadata line so the Markdown file is self-contained.
    The public article page already displays the title and keywords in the
    OpenKB layout, so remove those generated lines to avoid duplicate UI text.
    """
    cleaned = remove_openkb_internal_metadata(raw_markdown)

    # Remove the first Markdown H1 only when it matches the article title.
    lines = cleaned.splitlines()
    if lines:
        first_line = lines[0].strip()
        if first_line.startswith("#"):
            heading_text = first_line.lstrip("#").strip()
            if heading_text.lower() == title.strip().lower():
                lines = lines[1:]
                while lines and not lines[0].strip():
                    lines = lines[1:]
                cleaned = "\n".join(lines)

    # Remove the generated keywords line from the body. Keywords are displayed
    # below the article details panel instead.
    if suggested and suggested.keywords:
        cleaned = re.sub(
            r"\n*\*\*Keywords:\*\*\s*.*\s*$",
            "",
            cleaned,
            flags=re.IGNORECASE,
        ).rstrip()

    return cleaned


def is_safe_article_upload_src(tag, name, value):
    """Allow only local /wiki/uploads/<safe-image-filename> image sources."""
    if name != "src":
        return False

    prefix = "/wiki/uploads/"
    if not value.startswith(prefix):
        return False

    filename = value[len(prefix):]
    return is_allowed_article_image_filename(filename)


def article_html_attribute_filter(tag, name, value):
    """Attribute allow-list for sanitized rendered Markdown."""
    if tag == "img":
        if name == "src":
            return is_safe_article_upload_src(tag, name, value)
        if name in {"alt", "title"}:
            return True
        return False

    if tag == "a":
        return name in {"href", "title"}

    if tag in {"code", "pre"}:
        return name == "class"

    if tag in {"th", "td"}:
        return name in {"align", "colspan", "rowspan"}

    if tag in {"h1", "h2", "h3", "h4", "h5", "h6"}:
        return name == "id"

    return False


def render_safe_markdown(markdown_text):
    """Render Markdown and sanitize raw HTML before displaying an article."""
    html = markdown.markdown(
        markdown_text or "",
        extensions=["fenced_code", "tables", "toc"],
        output_format="html5",
    )

    allowed_tags = set(bleach.sanitizer.ALLOWED_TAGS) | {
        "p", "br", "hr",
        "h1", "h2", "h3", "h4", "h5", "h6",
        "pre", "span",
        "table", "thead", "tbody", "tr", "th", "td",
        "img",
    }

    return bleach.clean(
        html,
        tags=allowed_tags,
        attributes=article_html_attribute_filter,
        protocols=["http", "https", "mailto"],
        strip=True,
    )


def write_article_files(article, sync_ai=False, mark_ai_stale=True):
    """Mirror a SuggestedArticle into OpenKB raw and public wiki/source Markdown files.

    Full AI summary/index rebuilds are intentionally not done here. Article save,
    publish, import, and delete flows should stay fast, so they only mark the AI
    index as stale. The heavier sync runs on demand when Ask OpenKB AI is used.
    The sync_ai argument is kept for backward compatibility with older callers.
    """
    init_openkb_storage()

    ensure_article_filename(article)

    raw_file_path = settings.OPENKB_RAW_DIR / article.filename
    sources_dir = settings.OPENKB_WIKI_DIR / "sources"
    wiki_file_path = sources_dir / article.filename

    markdown_content = build_article_markdown(article)

    raw_file_path.write_text(markdown_content, encoding="utf-8")

    if article.status == SuggestedArticle.Status.PUBLISHED:
        wiki_file_path.write_text(markdown_content, encoding="utf-8")
    elif wiki_file_path.exists():
        wiki_file_path.unlink()

    article.raw_path = raw_file_path.relative_to(settings.OPENKB_DATA_DIR).as_posix()
    article.wiki_path = f"sources/{article.filename}"

    SuggestedArticle.objects.filter(pk=article.pk).update(
        filename=article.filename,
        raw_path=article.raw_path,
        wiki_path=article.wiki_path,
    )

    if mark_ai_stale or sync_ai:
        mark_openkb_ai_stale("Article Markdown files changed.")


def delete_article_files(article):
    """Delete Markdown files and image assets for a user-owned article."""
    candidates = []

    if article.raw_path:
        candidates.append((settings.OPENKB_DATA_DIR / article.raw_path, settings.OPENKB_DATA_DIR))

    if article.wiki_path:
        candidates.append((settings.OPENKB_WIKI_DIR / article.wiki_path, settings.OPENKB_WIKI_DIR))

    for file_path, root_dir in candidates:
        file_path = file_path.resolve()
        root_dir = root_dir.resolve()

        if str(file_path).startswith(str(root_dir)) and file_path.exists() and file_path.is_file():
            file_path.unlink()

    for filename in (article.image_assets or extract_article_image_filenames(article.body)):
        if not image_is_used_by_other_article(filename, current_article=article):
            delete_uploaded_image_file(filename)

    mark_openkb_ai_stale("Article Markdown files deleted.")


def get_article_metadata_by_wiki_path(wiki_path):
    try:
        return SuggestedArticle.objects.select_related("owner").get(
            wiki_path=wiki_path,
            status=SuggestedArticle.Status.PUBLISHED,
        )
    except SuggestedArticle.DoesNotExist:
        return None


def record_article_session_view(request, article):
    """Increment an article view count once per browser session.

    This prevents simple page refreshes from repeatedly increasing the counter.
    A different browser/session can still count as a new view.
    """
    if not article or not article.pk:
        return

    session_key = "viewed_suggested_article_ids"
    viewed_ids = request.session.get(session_key, [])
    article_key = str(article.pk)

    if article_key in viewed_ids:
        return

    SuggestedArticle.objects.filter(pk=article.pk).update(view_count=F("view_count") + 1)
    article.view_count = (article.view_count or 0) + 1

    viewed_ids.append(article_key)
    request.session[session_key] = viewed_ids[-1000:]
    request.session.modified = True


def get_openkb_wiki_articles(sort_by_views=False):
    """Return public article cards from published Django articles only.

    Raw /wiki/*.md files are no longer treated as public pages. OpenKB still
    uses wiki/sources internally for AI indexing, but the website links to the
    safe Django article route instead of exposing Markdown file paths.
    """
    articles = []

    queryset = SuggestedArticle.objects.select_related("owner").filter(
        status=SuggestedArticle.Status.PUBLISHED,
    )

    for suggested in queryset:
        modified_at = timezone.localtime(suggested.updated_at).strftime("%Y-%m-%d %H:%M")
        articles.append({
            "title": suggested.title,
            "type": "Article",
            "date": modified_at,
            "views": suggested.view_count or 0,
            "url": suggested.public_url,
            "path": "",
            "raw_markdown": build_article_markdown(suggested),
            "author": suggested.author_display,
            "keywords": suggested.keyword_list,
            "suggested_id": suggested.pk,
        })

    if sort_by_views:
        articles.sort(
            key=lambda item: (item.get("views") or 0, item.get("date") or ""),
            reverse=True,
        )
    else:
        articles.sort(key=lambda item: item["date"], reverse=True)
    return articles


def is_ldap_managed_user(user):
    """Return True only when the stored profile marks this as an AD account.

    Do not infer AD status from email domain. A local Django user may have a
    company-style email such as alice@openkb.local and must still be allowed to
    use local password management.
    """
    profile = getattr(user, "kb_profile", None)
    return bool(profile and profile.is_ldap_type)


def get_user_profile(user):
    if not user.is_authenticated:
        return None

    profile, created = UserProfile.objects.get_or_create(user=user)

    # Keep legacy role values consistent with the explicit source column.
    # The source column decides Local vs AD. The account_type field remains for
    # role/backward-compatibility, so it is aligned to Local User/Admin or AD User/Admin.
    role_is_admin = profile.account_type in {
        UserProfile.AccountType.ADMIN,
        UserProfile.AccountType.LDAP_ADMIN,
    }
    if profile.auth_source == UserProfile.AuthSource.ACTIVE_DIRECTORY:
        desired_account_type = UserProfile.AccountType.LDAP_ADMIN if role_is_admin else UserProfile.AccountType.LDAP_USER
    else:
        desired_account_type = UserProfile.AccountType.ADMIN if role_is_admin else UserProfile.AccountType.USER
    if profile.account_type != desired_account_type:
        profile.account_type = desired_account_type
        profile.save(update_fields=["account_type", "updated_at"])

    # Keep existing superuser/staff accounts visible as Admin unless already LDAP admin.
    if (user.is_superuser or user.is_staff) and profile.account_type not in {
        UserProfile.AccountType.ADMIN,
        UserProfile.AccountType.LDAP_ADMIN,
    }:
        profile.account_type = UserProfile.AccountType.ADMIN
        profile.save(update_fields=["account_type", "updated_at"])

    return profile


def user_can_access_main_site(user):
    if not user.is_authenticated or not user.is_active:
        return False

    profile = get_user_profile(user)
    return bool(profile and profile.can_access_main_site)


def main_site_login_required(view_func):
    @wraps(view_func)
    @login_required
    def wrapper(request, *args, **kwargs):
        if not user_can_access_main_site(request.user):
            logout(request)
            return redirect("home")
        return view_func(request, *args, **kwargs)

    return wrapper


def get_account_type_display(user):
    profile = get_user_profile(user)
    if not profile:
        return ""

    if profile.is_ldap_type:
        if profile.is_admin_type:
            return "AD Admin"
        return "AD User"

    if profile.is_admin_type:
        return "Local Admin"
    return "Local User"

def format_profile_display_name(user):
    full_name = user.get_full_name().strip()
    return full_name or user.get_username()


def paginate_articles(request, articles, per_page=20):
    """Paginate article lists safely for the index/search page."""
    paginator = Paginator(articles, per_page)
    page_number = request.GET.get("page", 1)

    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    return page_obj


def tokenize_search_query(value):
    """Return meaningful lowercase search tokens for ranking and related articles."""
    return [
        word
        for word in re.findall(r"[a-zA-Z0-9]+", (value or "").lower())
        if len(word) >= 2 and word not in SEARCH_STOPWORDS
    ]


def strip_markdown_for_search(markdown_text):
    """Create lightweight plain text from Markdown for snippets and ranking.

    Public search snippets should not expose internal Django/OpenKB metadata such
    as generated-by comments, article IDs, or generated keyword lines.
    """
    text = remove_openkb_internal_metadata(markdown_text)
    text = re.sub(r"^---.*?---", " ", text, flags=re.DOTALL)
    text = re.sub(r"<!--.*?-->", " ", text, flags=re.DOTALL)
    text = re.sub(r"```.*?```", " ", text, flags=re.DOTALL)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    text = re.sub(r"!?\[([^\]]+)\]\([^\)]+\)", r"\1", text)
    text = re.sub(r"\*\*Keywords:\*\*\s*.*", " ", text, flags=re.IGNORECASE)
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"[#>*_~\-|]+", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def build_search_excerpt(raw_markdown, query_words, max_length=180):
    """Return a short result snippet around the first useful query token."""
    plain_text = strip_markdown_for_search(raw_markdown)
    if not plain_text:
        return ""

    lower_text = plain_text.lower()
    first_match = -1
    for word in query_words:
        index = lower_text.find(word)
        if index >= 0 and (first_match == -1 or index < first_match):
            first_match = index

    if first_match < 0:
        return plain_text[:max_length].rstrip() + ("…" if len(plain_text) > max_length else "")

    start = max(0, first_match - 70)
    end = min(len(plain_text), start + max_length)
    snippet = plain_text[start:end].strip()
    if start > 0:
        snippet = "…" + snippet
    if end < len(plain_text):
        snippet = snippet + "…"
    return snippet


def score_article_for_query(article, query):
    """Score one public article for a user query. Higher means more relevant."""
    query = (query or "").strip().lower()
    query_words = tokenize_search_query(query)
    if not query and not query_words:
        return 0

    title = (article.get("title") or "").lower()
    raw_markdown = article.get("raw_markdown") or ""
    body = strip_markdown_for_search(raw_markdown).lower()
    keywords = " ".join(article.get("keywords") or []).lower()
    path = (article.get("path") or "").lower()
    author = (article.get("author") or "").lower()

    score = 0

    if query:
        if title == query:
            score += 150
        elif query in title:
            score += 90
        if query in keywords:
            score += 70
        if query in body:
            score += 35
        if query in path:
            score += 15

    matched_words = 0
    for word in query_words:
        word_score = 0
        if word in title:
            word_score += 20
        if word in keywords:
            word_score += 16
        if word in path:
            word_score += 7
        if word in author:
            word_score += 4

        body_hits = body.count(word)
        if body_hits:
            word_score += min(body_hits, 8) * 2

        if word_score:
            matched_words += 1
            score += word_score

    if query_words and matched_words == len(query_words):
        score += 30
    elif query_words and matched_words:
        score += matched_words * 3

    # Small tie-breakers: stronger source files, viewed articles, then recent files.
    if (article.get("type") or "").lower() == "openkb source":
        score += 5
    score += min(int(article.get("views") or 0), 50)

    return score


def rank_articles_for_query(articles, query):
    """Return matching articles sorted by relevance for the search page."""
    query_words = tokenize_search_query(query)
    ranked = []

    for article in articles:
        score = score_article_for_query(article, query)
        if score <= 0:
            continue

        item = dict(article)
        item["search_score"] = score
        item["search_excerpt"] = build_search_excerpt(item.get("raw_markdown", ""), query_words)
        ranked.append(item)

    ranked.sort(
        key=lambda item: (
            item.get("search_score") or 0,
            item.get("views") or 0,
            item.get("date") or "",
        ),
        reverse=True,
    )
    return ranked


def get_contextual_related_articles(current_article, limit=5):
    """Return article-page related links using title, keywords, body overlap, and views."""
    if not current_article:
        return []

    current_path = current_article.get("path") or ""
    current_keywords = " ".join(current_article.get("keywords") or [])
    current_title = current_article.get("title") or ""
    body_tokens = tokenize_search_query(strip_markdown_for_search(current_article.get("raw_markdown") or ""))
    unique_body_tokens = list(dict.fromkeys(body_tokens))[:30]
    related_query = " ".join([current_title, current_keywords, " ".join(unique_body_tokens)]).strip()

    candidates = [
        article
        for article in get_openkb_wiki_articles(sort_by_views=True)
        if article.get("path") != current_path
    ]

    scored = []
    for article in candidates:
        score = score_article_for_query(article, related_query)
        if score > 0:
            item = dict(article)
            item["related_score"] = score
            scored.append(item)

    scored.sort(
        key=lambda item: (
            item.get("related_score") or 0,
            item.get("views") or 0,
            item.get("date") or "",
        ),
        reverse=True,
    )

    # Fallback to trending/recent articles if the article has too little text to match.
    if len(scored) < limit:
        seen = {item.get("path") for item in scored}
        for article in candidates:
            if article.get("path") in seen:
                continue
            scored.append(article)
            seen.add(article.get("path"))
            if len(scored) >= limit:
                break

    return scored[:limit]


def get_profile_account_context(user):
    user_is_ldap_managed = is_ldap_managed_user(user)
    profile, created = UserProfile.objects.get_or_create(user=user)
    mfa_device = getattr(user, "kb_mfa_device", None)
    mfa_required = user_requires_mfa(user)

    return {
        "total_user_article_count": SuggestedArticle.objects.filter(owner=user).count(),
        "profile_display_name": format_profile_display_name(user),
        "user_is_ldap_managed": user_is_ldap_managed,
        "account_type_display": get_account_type_display(user),
        "auth_source_display": profile.get_auth_source_display(),
        "is_local_account": not user_is_ldap_managed,
        "can_change_local_password": user.has_usable_password() and not user_is_ldap_managed,
        "can_confirm_profile_changes": user.has_usable_password(),
        "can_use_admin_tools": user_can_use_admin_tools(user),
        "profile_preferred_language": profile.preferred_language,
        "supported_languages": settings.LANGUAGES,
        "mfa_required": mfa_required,
        "local_mfa_required": mfa_required,  # backwards-compatible template key
        "mfa_device": mfa_device,
        "mfa_enabled": bool(mfa_device and mfa_device.confirmed),
        "mfa_last_verified_at": getattr(mfa_device, "last_verified_at", None),
    }


def validate_profile_password_policy(password, user):
    """Return password policy issues for the profile change-password form.

    This enforces the local project policy used for Django-managed accounts:
    minimum length plus uppercase, lowercase, number, and special character.
    LDAP-managed users should change passwords through LDAP/AD instead.
    """
    issues = []

    if len(password) < 12:
        issues.append("Password must be at least 12 characters long.")
    if not re.search(r"[A-Z]", password):
        issues.append("Password must include at least 1 uppercase letter.")
    if not re.search(r"[a-z]", password):
        issues.append("Password must include at least 1 lowercase letter.")
    if not re.search(r"[0-9]", password):
        issues.append("Password must include at least 1 number.")
    if not re.search(r"[^A-Za-z0-9]", password):
        issues.append("Password must include at least 1 special character.")

    lower_password = password.lower()
    username = (user.get_username() or "").lower()
    email_name = (user.email or "").split("@")[0].lower()

    if username and len(username) >= 3 and username in lower_password:
        issues.append("Password must not contain your username.")
    if email_name and len(email_name) >= 3 and email_name in lower_password:
        issues.append("Password must not contain the name part of your email address.")

    return issues


def run_openkb_query(question):
    """Call the local bundled OpenKB CLI against the synced Django OpenKB data."""
    init_openkb_storage()
    ensure_openkb_ai_synced()

    env = os.environ.copy()

    if getattr(settings, "LLM_API_KEY", ""):
        env["LLM_API_KEY"] = settings.LLM_API_KEY

    if getattr(settings, "GEMINI_API_KEY", ""):
        env["GEMINI_API_KEY"] = settings.GEMINI_API_KEY

    env["OPENKB_AI_PROVIDER"] = "openkb-cli"
    env["OPENKB_GEMINI_MODEL"] = getattr(settings, "OPENKB_GEMINI_MODEL", "gemini/gemini-2.5-flash")
    env["LITELLM_DROP_PARAMS"] = "true"
    env["DROP_PARAMS"] = "true"
    env["OPENKB_DIR"] = str(settings.OPENKB_DATA_DIR)
    env["PYTHONPATH"] = (
        str(settings.OPENKB_BASE_DIR)
        + os.pathsep
        + env.get("PYTHONPATH", "")
    )

    command = (
        "import sys; "
        "import litellm; "
        "litellm.drop_params = True; "
        f"sys.path.insert(0, {str(settings.OPENKB_BASE_DIR)!r}); "
        "from openkb.cli import cli; "
        "cli.main("
        "args=['--kb-dir', sys.argv[2], 'query', sys.argv[1]], "
        "prog_name='openkb', "
        "standalone_mode=False"
        ")"
    )

    result = subprocess.run(
        [sys.executable, "-c", command, question, str(settings.OPENKB_DATA_DIR)],
        cwd=str(settings.BASE_DIR),
        env=env,
        capture_output=True,
        text=True,
        timeout=180,
    )

    if result.returncode != 0:
        raise RuntimeError(result.stderr or result.stdout or "openkb query failed")

    return result.stdout.strip()


OPENKB_AI_SMALL_TALK_PATTERNS = [
    r"^hi+$",
    r"^hi\s+there[!.?]*$",
    r"^hello+$",
    r"^hello\s+there[!.?]*$",
    r"^hey+$",
    r"^hey\s+there[!.?]*$",
    r"^are\s+you\s+there[?.!]*$",
    r"^are\s+you\s+still\s+there[?.!]*$",
    r"^are\s+you\s+still\s+here[?.!]*$",
    r"^you\s+there[?.!]*$",
    r"^test[?.!]*$",
    r"^testing[?.!]*$",
]


def is_openkb_small_talk_request(question):
    """Return True for greetings/status checks that should not trigger article search.

    Without this guard, a short message such as "hi there" can accidentally
    match published articles because generic words appear in article bodies.
    """
    prompt = re.sub(r"\s+", " ", (question or "").strip().lower())
    if not prompt:
        return False

    if len(prompt) <= 80:
        for pattern in OPENKB_AI_SMALL_TALK_PATTERNS:
            if re.fullmatch(pattern, prompt):
                return True

    tokens = tokenize_search_query(prompt)
    return not tokens and len(prompt) <= 80


def build_openkb_small_talk_answer(question=None):
    """Return a normal chat response for greetings/status messages."""
    prompt = ((question or "").strip().lower())
    if "still" in prompt or "there" in prompt or "here" in prompt:
        return "Yes, I’m here. Ask me a question about the knowledge base, or ask me to recommend published articles."
    if "test" in prompt:
        return "OpenKB AI is ready. Ask me a knowledge-base question or request relevant articles."
    return "Hello! I’m OpenKB AI. Ask me a question about the knowledge base, or ask me to recommend published articles."


OPENKB_AI_ARTICLE_INTENT_TERMS = [
    "article", "articles",
    "related article", "related articles",
    "recommend article", "recommend articles",
    "recommendation", "recommendations",
    "source", "sources",
    "reference", "references",
    "link", "links",
    "where can i read", "where to read",
    "documentation", "docs",
    "show article", "show articles",
    "find article", "find articles",
    "relevant article", "relevant articles",
    "anything about", "any article", "any articles",
    "is there any article", "is there any articles",
]


def is_openkb_article_recommendation_request(question):
    """Return True when the user is mainly asking for article links.

    These requests should be answered from the local published-article database
    first, without waiting for the external LLM provider. This keeps the chatbox
    useful for anonymous users and logged-in users even when Gemini/LiteLLM is
    slow, rate-limited, or unavailable.
    """
    prompt = (question or "").lower()
    return any(term in prompt for term in OPENKB_AI_ARTICLE_INTENT_TERMS)


def normalize_openkb_article_query(question):
    """Remove chat/request filler words so article search can match titles better."""
    query = (question or "").strip()

    quoted = re.findall(r"[\"']([^\"']{2,})[\"']", query)
    if quoted:
        return " ".join(quoted).strip()

    cleaned = query.lower()
    replacements = [
        "is there any articles about", "is there any article about",
        "are there any articles about", "are there any article about",
        "is there any articles on", "is there any article on",
        "are there any articles on", "are there any article on",
        "any relevant articles on", "any relevant article on",
        "any relevant articles about", "any relevant article about",
        "any articles about", "any article about",
        "any articles on", "any article on",
        "articles about", "article about",
        "articles on", "article on",
        "recommend articles about", "recommend article about",
        "recommend articles on", "recommend article on",
        "find articles about", "find article about",
        "find articles on", "find article on",
        "show articles about", "show article about",
        "show articles on", "show article on",
        "anything about", "something about",
        "relevant article", "relevant articles",
        "published article", "published articles",
        "wiki article", "wiki articles",
        "documentation", "docs",
        "please", "can you", "could you", "help me",
    ]
    for phrase in replacements:
        cleaned = cleaned.replace(phrase, " ")

    cleaned = re.sub(r"[^a-z0-9@._\- ]+", " ", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned or query


def find_related_openkb_articles(question, limit=5, minimum_score=None):
    """Find strongly related published articles for Ask OpenKB AI.

    This searches Django-published articles directly instead of depending on the
    external OpenKB/Gemini answer. It is safe for anonymous users because it only
    returns public article titles/URLs that the website already exposes.
    """
    init_openkb_storage()

    # Do not recommend articles for greetings or very short chat filler.
    # This prevents messages like "hi there" from returning random trending
    # articles when the external provider is unavailable.
    if is_openkb_small_talk_request(question):
        return []

    article_query = normalize_openkb_article_query(question)
    query_words = tokenize_search_query(article_query)

    # If the user did not clearly ask for articles and the query has no useful
    # searchable keywords, there is nothing safe to recommend.
    if not is_openkb_article_recommendation_request(question) and not query_words:
        return []

    ranked_articles = rank_articles_for_query(get_openkb_wiki_articles(), article_query)

    if not ranked_articles and article_query != (question or ""):
        ranked_articles = rank_articles_for_query(get_openkb_wiki_articles(), question)

    if minimum_score is None:
        minimum_score = 10 if is_openkb_article_recommendation_request(question) else 35

    results = []
    seen_keys = set()

    for item in ranked_articles:
        key = item.get("suggested_id") or item.get("url") or item.get("path") or item.get("title")
        if not key or key in seen_keys:
            continue

        if int(item.get("search_score") or 0) < int(minimum_score):
            continue

        seen_keys.add(key)
        results.append({
            "title": item.get("title", "Untitled"),
            "url": item.get("url") or (f"/wiki/{item.get('path')}" if item.get("path") else "#"),
            "snippet": item.get("search_excerpt") or "",
        })

        if len(results) >= limit:
            break

    return results

def build_openkb_article_recommendation_answer(question, related_articles):
    """Create a concise chat answer for article/link requests."""
    if related_articles:
        count = len(related_articles)
        article_word = "article" if count == 1 else "articles"
        return f"I found {count} relevant published {article_word}."

    cleaned_query = normalize_openkb_article_query(question)
    if cleaned_query and cleaned_query != (question or ""):
        return (
            f"I could not find a matching published article for '{cleaned_query}'. "
            "Try another keyword or check whether the article is published."
        )

    return "I could not find a matching published article. Try another keyword or check whether the article is published."


def get_client_ip(request):
    """Return the best available client IP, respecting the nginx proxy header."""
    forwarded_for = request.META.get("HTTP_X_FORWARDED_FOR")
    if forwarded_for:
        return forwarded_for.split(",")[0].strip()
    return request.META.get("REMOTE_ADDR", "unknown")


def get_openkb_ai_rate_identifier(request):
    """Rate-limit logged-in users by user id, anonymous visitors by IP."""
    if request.user.is_authenticated:
        return f"user:{request.user.pk}"
    return f"ip:{get_client_ip(request)}"


def check_openkb_ai_rate_limit(request):
    """Return (allowed, retry_after_seconds). Log when a user/IP is blocked."""
    identifier = get_openkb_ai_rate_identifier(request)
    now = int(time.time())

    window_seconds = settings.OPENKB_AI_RATE_LIMIT_WINDOW_SECONDS
    max_requests = settings.OPENKB_AI_RATE_LIMIT_MAX_REQUESTS
    block_seconds = settings.OPENKB_AI_RATE_LIMIT_BLOCK_SECONDS

    block_key = f"openkb_ai:block:{identifier}"
    if cache.get(block_key):
        logger.warning(
            "OpenKB AI blocked request while temporary block is active: identifier=%s ip=%s user_id=%s",
            identifier,
            get_client_ip(request),
            request.user.pk if request.user.is_authenticated else "anonymous",
        )
        return False, block_seconds

    attempts_key = f"openkb_ai:attempts:{identifier}"
    attempts = cache.get(attempts_key, [])
    attempts = [timestamp for timestamp in attempts if now - timestamp < window_seconds]

    if len(attempts) >= max_requests:
        cache.set(block_key, True, block_seconds)
        cache.set(attempts_key, attempts, window_seconds)
        logger.warning(
            "OpenKB AI rate limit exceeded: identifier=%s ip=%s user_id=%s attempts=%s window_seconds=%s block_seconds=%s",
            identifier,
            get_client_ip(request),
            request.user.pk if request.user.is_authenticated else "anonymous",
            len(attempts),
            window_seconds,
            block_seconds,
        )
        return False, block_seconds

    attempts.append(now)
    cache.set(attempts_key, attempts, window_seconds)
    return True, 0


def clean_openkb_ai_answer(answer):
    """Hide internal OpenKB/source-path details before showing AI output."""
    cleaned = remove_openkb_internal_metadata(answer)

    # Remove internal source path bullets/lines that OpenKB may echo from summaries.
    cleaned = re.sub(
        r"(?im)^\s*[-*]?\s*(?:\*\*)?full\s+article\s+path(?:\*\*)?\s*:?\s*`?[^\n`]+`?\s*$",
        "",
        cleaned,
    )
    cleaned = re.sub(
        r"(?im)^\s*[-*]?\s*openkb\s+source\s*/\s*sources/[^\n]+$",
        "",
        cleaned,
    )
    cleaned = re.sub(
        r"(?im)^\s*[-*]?\s*source\s*:?\s*`?(?:sources|summaries)/[^\n`]+`?\s*$",
        "",
        cleaned,
    )
    cleaned = re.sub(
        r"(?im)^\s*[-*]?\s*`?(?:sources|summaries)/[^\n`]+\.md`?\s*$",
        "",
        cleaned,
    )

    # Collapse excess blank lines left by removed metadata.
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned).strip()
    return cleaned


def answer_indicates_no_openkb_match(answer):
    """Detect common no-result answers so we do not recommend random articles."""
    lowered = (answer or "").lower()
    no_match_phrases = [
        "couldn't find any information",
        "could not find any information",
        "i couldn't find",
        "i could not find",
        "no information",
        "not find information",
        "not found in the wiki",
        "not in the wiki",
        "no relevant",
        "no matching",
        "nothing about",
    ]
    return any(phrase in lowered for phrase in no_match_phrases)


def should_show_openkb_related_articles(question, answer, related_articles=None):
    """Show article recommendations when there are matching public articles."""
    if related_articles is not None:
        return bool(related_articles)

    if answer_indicates_no_openkb_match(answer):
        return False

    return is_openkb_article_recommendation_request(question)


def clean_openkb_ai_error_message(error):
    """Return a user-friendly AI error while detailed info remains in logs."""
    text = str(error or "")
    lowered = text.lower()

    if (
        "429" in lowered
        or "ratelimit" in lowered
        or "rate limit" in lowered
        or "quota" in lowered
        or "resource_exhausted" in lowered
        or "too many requests" in lowered
    ):
        return "OpenKB AI is temporarily unavailable. Please try again later or contact IT support if the issue persists."

    if "503" in lowered or "serviceunavailable" in lowered or "high demand" in lowered or "unavailable" in lowered:
        return "OpenKB AI is temporarily unavailable. Please try again later or contact IT support if the issue persists."

    if "timeout" in lowered:
        return "OpenKB AI took too long to respond. Please try again later or contact IT support if the issue persists."

    return "OpenKB AI could not complete the request. Please try again later or contact IT support if the issue persists."


def redact_openkb_debug_text(text, max_chars=2000):
    """Return debug text for logs without exposing common API-key formats."""
    value = str(text or "")[:max_chars]

    # Gemini API keys often begin with AIza. Keep only the prefix so logs prove
    # a key existed without leaking the full secret.
    value = re.sub(r"AIza[0-9A-Za-z_\-]{20,}", "AIza...REDACTED", value)

    # Generic Authorization/Bearer/key patterns seen in SDK/provider errors.
    value = re.sub(r"(?i)(authorization\s*[:=]\s*bearer\s+)[^\s,;]+", r"\1REDACTED", value)
    value = re.sub(r"(?i)((?:api[_-]?key|key)\s*[:=]\s*)[^\s,;]+", r"\1REDACTED", value)

    return value


def openkb_ai_output_indicates_error(output):
    """Detect CLI error text that was printed as output instead of raised."""
    lowered = (output or "").lower().strip()
    if not lowered:
        return False
    error_markers = [
        "[error] query failed",
        "litellm.ratelimiterror",
        "litellm.serviceunavailableerror",
        "geminiexception",
        "resource_exhausted",
        "quota exceeded",
        "you exceeded your current quota",
    ]
    return any(marker in lowered for marker in error_markers)
