"""
Django settings for djopenkb project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""

import os
from pathlib import Path

from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# ---------------------------------------------------------------------
# OpenKB paths
# ---------------------------------------------------------------------

OPENKB_BASE_DIR = BASE_DIR / os.getenv("OPENKB_BASE_DIR", "OpenKB-main")

OPENKB_DATA_DIR = BASE_DIR / os.getenv("OPENKB_DATA_DIR", "openkb-data")
OPENKB_RAW_DIR = OPENKB_DATA_DIR / "raw"
OPENKB_WIKI_DIR = OPENKB_DATA_DIR / "wiki"

OPENKB_CONTENT_DIR = BASE_DIR / "kb-content"
OPENKB_ARTICLES_DIR = OPENKB_CONTENT_DIR / "articles"


# ---------------------------------------------------------------------
# OpenKB AI chatbot / LiteLLM config
# ---------------------------------------------------------------------

# These settings are for the optional Ask OpenKB AI chat box only.
# Django locale/.po files are still used for UI translation, and article
# translation is intentionally NOT done by AI.
OPENKB_AI_PROVIDER = os.getenv("OPENKB_AI_PROVIDER", "openkb-cli")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
LLM_API_KEY = os.getenv("LLM_API_KEY", "")
OPENKB_GEMINI_MODEL = os.getenv("OPENKB_GEMINI_MODEL", "gemini/gemini-2.5-flash")
LITELLM_DROP_PARAMS = os.getenv("LITELLM_DROP_PARAMS", "true")

# Safety limits for the public Ask OpenKB AI endpoint.
# These values can be overridden in your root .env file.
OPENKB_AI_MAX_PROMPT_CHARS = int(os.getenv("OPENKB_AI_MAX_PROMPT_CHARS", "1000"))
OPENKB_AI_RATE_LIMIT_MAX_REQUESTS = int(os.getenv("OPENKB_AI_RATE_LIMIT_MAX_REQUESTS", "5"))
OPENKB_AI_RATE_LIMIT_WINDOW_SECONDS = int(os.getenv("OPENKB_AI_RATE_LIMIT_WINDOW_SECONDS", "60"))
OPENKB_AI_RATE_LIMIT_BLOCK_SECONDS = int(os.getenv("OPENKB_AI_RATE_LIMIT_BLOCK_SECONDS", "300"))


# ---------------------------------------------------------------------
# Django security / basics
# ---------------------------------------------------------------------

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-ja^jbb-_fb0tvu71u+&4-=e_-i52*wes=$hzm8xdj_0kx22nbj",
)

DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "web",
    "nginx",
]

CSRF_TRUSTED_ORIGINS = [
    "https://localhost:8080",
    "https://127.0.0.1:8080",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# ---------------------------------------------------------------------
# Application definition
# ---------------------------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "kb.apps.KbConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "kb.middleware.UserProfileLanguageMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "djopenkb.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "website" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.i18n",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "djopenkb.wsgi.application"


# ---------------------------------------------------------------------
# Cache / logging
# ---------------------------------------------------------------------

# Used for lightweight Ask OpenKB AI rate limiting. For multi-container
# production deployments, replace this with Redis or another shared cache.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "djopenkb-local-cache",
    }
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "kb": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_KB_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}


# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------

# PostgreSQL is the default database for this project.
# Docker Compose provides these POSTGRES_* values to the web container.
# For quick local testing outside Docker, set USE_SQLITE=true to temporarily use db.sqlite3.
USE_SQLITE = os.getenv("USE_SQLITE", "false").lower() == "true"

if USE_SQLITE:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "djopenkb"),
            "USER": os.getenv("POSTGRES_USER", "djopenkb"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", "djopenkb_password"),
            "HOST": os.getenv("POSTGRES_HOST", "db"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
        }
    }


# ---------------------------------------------------------------------
# Authentication / LDAP
# ---------------------------------------------------------------------

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

LDAP_ENABLED = os.getenv("LDAP_ENABLED", "false").lower() == "true"
LDAP_PLACEHOLDER_ENABLED = os.getenv("LDAP_PLACEHOLDER_ENABLED", "false").lower() == "true"
LDAP_PLACEHOLDER_AUTO_CREATE_USERS = os.getenv("LDAP_PLACEHOLDER_AUTO_CREATE_USERS", "false").lower() == "true"
LDAP_PLACEHOLDER_PASSWORD = os.getenv("LDAP_PLACEHOLDER_PASSWORD", "ChangeThisPlaceholderPassword123!")

if LDAP_ENABLED:
    try:
        import ldap
        from django_auth_ldap.config import LDAPSearch
    except ImportError as exc:
        raise ImportError(
            "LDAP_ENABLED=true but LDAP packages are missing. "
            "Make sure Dockerfile installs libldap2-dev, libsasl2-dev, ldap-utils, "
            "and pip installs django-auth-ldap."
        ) from exc

    AUTHENTICATION_BACKENDS = [
        "kb.backends.NextLabsLDAPBackend",
        "kb.backends.PlaceholderLDAPBackend",
        "kb.backends.EmailOrUsernameModelBackend",
    ]

    AUTH_LDAP_SERVER_URI = os.getenv(
        "LDAP_SERVER_URI",
        "ldap://your-ad-server.nextlabs.com:389",
    )

    AUTH_LDAP_BIND_DN = os.getenv("LDAP_BIND_DN", "")
    AUTH_LDAP_BIND_PASSWORD = os.getenv("LDAP_BIND_PASSWORD", "")

    AUTH_LDAP_USER_SEARCH = LDAPSearch(
        os.getenv("LDAP_USER_SEARCH_BASE", "DC=nextlabs,DC=com"),
        ldap.SCOPE_SUBTREE,
        os.getenv("LDAP_USER_FILTER", "(userPrincipalName=%(user)s)"),
    )

    AUTH_LDAP_USER_ATTR_MAP = {
        "first_name": "givenName",
        "last_name": "sn",
        "email": "mail",
    }

    AUTH_LDAP_ALWAYS_UPDATE_USER = True
    AUTH_LDAP_CREATE_USERS = True

    AUTH_LDAP_CONNECTION_OPTIONS = {
        ldap.OPT_REFERRALS: 0,
    }

    AUTH_LDAP_CACHE_TIMEOUT = 3600

else:
    AUTHENTICATION_BACKENDS = [
        "kb.backends.PlaceholderLDAPBackend",
        "kb.backends.EmailOrUsernameModelBackend",
    ]


# ---------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ---------------------------------------------------------------------
# Internationalization
# ---------------------------------------------------------------------

LANGUAGE_CODE = "en"

LANGUAGES = [
    ("en", "English"),
    ("de", "Deutsch"),
    ("da", "Dansk"),
    ("es", "Español"),
    ("zh-hans", "简体中文"),
    ("ru", "Русский"),
    ("pt-br", "Português do Brasil"),
    ("ja", "日本語"),
    ("fi", "Suomi"),
    ("sv", "Svenska"),
    ("tr", "Türkçe"),
    ("fa", "فارسی"),
    ("ms", "Bahasa Melayu"),
    ("ta", "தமிழ்"),
    ("fr", "Français"),
    ("it", "Italiano"),
    ("ko", "한국어"),
    ("id", "Bahasa Indonesia"),
    ("th", "ไทย"),
    ("vi", "Tiếng Việt"),
    ("nl", "Nederlands"),
    ("pl", "Polski"),
    ("ar", "العربية"),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

LANGUAGE_COOKIE_AGE = 60 * 60 * 24 * 365
LANGUAGE_COOKIE_SAMESITE = "Lax"

TIME_ZONE = "Asia/Singapore"

USE_I18N = True

USE_TZ = True


# ---------------------------------------------------------------------
# Static files
# ---------------------------------------------------------------------

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "website" / "static",
]

# ---------------------------------------------------------------------
# Default primary key field type
# ---------------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"