"""
Django settings for djopenkb project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# Original VectifyAI/OpenKB source folder
OPENKB_BASE_DIR = BASE_DIR / os.getenv("OPENKB_BASE_DIR", "OpenKB-main")

# Actual initialized OpenKB data folder
OPENKB_DATA_DIR = BASE_DIR / os.getenv("OPENKB_DATA_DIR", "openkb-data")
OPENKB_RAW_DIR = OPENKB_DATA_DIR / "raw"
OPENKB_WIKI_DIR = OPENKB_DATA_DIR / "wiki"

# Old Django article folder, only for old links if needed
OPENKB_CONTENT_DIR = BASE_DIR / "kb-content"
OPENKB_ARTICLES_DIR = OPENKB_CONTENT_DIR / "articles"

# Original OpenKB CLI / LiteLLM config
OPENKB_AI_PROVIDER = os.getenv("OPENKB_AI_PROVIDER", "openkb-cli")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
LLM_API_KEY = os.getenv("LLM_API_KEY", "")
OPENKB_GEMINI_MODEL = os.getenv("OPENKB_GEMINI_MODEL", "gemini/gemini-2.5-flash")
LITELLM_DROP_PARAMS = os.getenv("LITELLM_DROP_PARAMS", "true")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ja^jbb-_fb0tvu71u+&4-=e_-i52*wes=$hzm8xdj_0kx22nbj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "kb", #OpenKB
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djopenkb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "website" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djopenkb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "website" / "static",
]
