"""
Django settings for djopenkb project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""

import json
import os
import urllib.error
import urllib.request
from pathlib import Path
from urllib.parse import urlparse

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent

# Optional: keep a local .env for non-secret development settings only.
# Sensitive values can be loaded from HashiCorp Vault instead.
load_dotenv(BASE_DIR / ".env")


_VAULT_SECRET_CACHE = None


def _read_text_file(path: str) -> str:
    return Path(path).read_text(encoding="utf-8").strip()


def env_or_file(name: str, default: str = "") -> str:
    """Read NAME, or NAME_FILE if configured.

    This supports Docker secrets-style file mounts, for example:
    DJANGO_SECRET_KEY_FILE=/run/secrets/django_secret_key
    """
    file_path = os.getenv(f"{name}_FILE", "").strip()
    if file_path:
        return _read_text_file(file_path)
    return os.getenv(name, default)


def _load_vault_secrets() -> dict:
    """Load the Knowledge Repository secret bundle from Vault KV v2.

    Expected Vault path by default:
      secret/data/djopenkb

    This intentionally has no third-party dependency such as hvac, so the
    project can fetch secrets with the Python standard library.
    """
    global _VAULT_SECRET_CACHE
    if _VAULT_SECRET_CACHE is not None:
        return _VAULT_SECRET_CACHE

    if os.getenv("VAULT_ENABLED", "false").lower() != "true":
        _VAULT_SECRET_CACHE = {}
        return _VAULT_SECRET_CACHE

    addr = os.getenv("VAULT_ADDR", "http://vault:8200").rstrip("/")
    mount = os.getenv("VAULT_KV_MOUNT", "secret").strip("/") or "secret"
    secret_path = os.getenv("VAULT_SECRET_PATH", "djopenkb").strip("/") or "djopenkb"

    token = os.getenv("VAULT_TOKEN", "").strip()
    token_file = os.getenv("VAULT_TOKEN_FILE", "").strip()
    if not token and token_file:
        token = _read_text_file(token_file)

    if not token:
        raise RuntimeError("VAULT_ENABLED=true but VAULT_TOKEN or VAULT_TOKEN_FILE is not configured.")

    url = f"{addr}/v1/{mount}/data/{secret_path}"
    req = urllib.request.Request(url, headers={"X-Vault-Token": token})

    try:
        with urllib.request.urlopen(req, timeout=int(os.getenv("VAULT_TIMEOUT", "5"))) as resp:
            payload = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"Unable to read Vault secret {mount}/{secret_path}: HTTP {exc.code} {detail}") from exc
    except Exception as exc:
        raise RuntimeError(f"Unable to read Vault secret {mount}/{secret_path}: {exc}") from exc

    _VAULT_SECRET_CACHE = payload.get("data", {}).get("data", {}) or {}
    return _VAULT_SECRET_CACHE


def secret_value(name: str, default: str = "") -> str:
    """Read a sensitive setting from file/env/Vault, in that order.

    Keeping env/file first is useful for tests and emergency overrides. In normal
    Vault mode, do not set the plain env var; store the value in Vault instead.
    """
    file_value = os.getenv(f"{name}_FILE", "").strip()
    if file_value:
        return _read_text_file(file_value)

    env_value = os.getenv(name)
    if env_value not in (None, ""):
        return env_value

    vault_value = _load_vault_secrets().get(name)
    if vault_value not in (None, ""):
        return str(vault_value)

    return default


def config_value(name: str, default: str = "") -> str:
    """Read a non-secret runtime config value from file/env/Vault.

    This keeps deployment-specific values such as LDAP_SERVER_URI outside the
    Docker image. Prefer .env for non-secret config, but Vault also works if you
    want all runtime values managed centrally.
    """
    return secret_value(name, default)


# ---------------------------------------------------------------------
# OpenKB paths
# ---------------------------------------------------------------------

OPENKB_BASE_DIR = BASE_DIR / os.getenv("OPENKB_BASE_DIR", "OpenKB-main")

OPENKB_DATA_DIR = BASE_DIR / os.getenv("OPENKB_DATA_DIR", "openkb-data")
OPENKB_RAW_DIR = OPENKB_DATA_DIR / "raw"
OPENKB_WIKI_DIR = OPENKB_DATA_DIR / "wiki"

# Separate filesystem scope for internal AI retrieval. The public OpenKB data
# directory must never contain internal/private article source files.
OPENKB_INTERNAL_DATA_DIR = BASE_DIR / os.getenv("OPENKB_INTERNAL_DATA_DIR", "openkb-data-internal")

OPENKB_CONTENT_DIR = BASE_DIR / "kb-content"
OPENKB_ARTICLES_DIR = OPENKB_CONTENT_DIR / "articles"


# ---------------------------------------------------------------------
# OpenKB AI chatbot / LiteLLM config
# ---------------------------------------------------------------------

# These settings are for the optional Ask OpenKB AI chat box only.
# Django locale/.po files are still used for UI translation, and article
# translation is intentionally NOT done by AI.
OPENKB_AI_PROVIDER = config_value("OPENKB_AI_PROVIDER", "openkb-cli")
AI_API_KEY = secret_value("AI_API_KEY", "")

# General LiteLLM/OpenKB model name.
# Use OPENKB_AI_MODEL for all providers, for example:
#   gemini/gemini-2.5-flash
#   openai/gpt-5.5
#   anthropic/claude-3-5-sonnet-latest
OPENKB_AI_MODEL = config_value("OPENKB_AI_MODEL", "gemini/gemini-2.5-flash").strip()

# Prefer provider-specific keys in production. AI_API_KEY is kept as a simple
# development fallback so the current free-tier key setup still works.
OPENAI_API_KEY = secret_value("OPENAI_API_KEY", "")
GEMINI_API_KEY = secret_value("GEMINI_API_KEY", "")
ANTHROPIC_API_KEY = secret_value("ANTHROPIC_API_KEY", "")

LITELLM_DROP_PARAMS = config_value("LITELLM_DROP_PARAMS", "true")


def int_config(name: str, default: int, minimum: int | None = None, maximum: int | None = None) -> int:
    """Read an integer config value with safe fallback/clamping."""
    try:
        value = int(config_value(name, str(default)))
    except (TypeError, ValueError):
        value = int(default)
    if minimum is not None:
        value = max(value, int(minimum))
    if maximum is not None:
        value = min(value, int(maximum))
    return value


def csv_int_config(name: str, default: str) -> list[int]:
    """Read comma-separated integer config, ignoring invalid entries."""
    values: list[int] = []
    for item in config_value(name, default).split(","):
        item = item.strip()
        if not item:
            continue
        try:
            value = int(item)
        except ValueError:
            continue
        if value > 0:
            values.append(value)
    return values or [int(part) for part in default.split(",") if part.strip().isdigit()]


# Safety limits for the Ask OpenKB AI endpoint.
# Redis/shared cache makes these limits work across multiple Gunicorn workers.
OPENKB_AI_MAX_PROMPT_CHARS = int_config("OPENKB_AI_MAX_PROMPT_CHARS", 1000, minimum=100, maximum=10000)
OPENKB_AI_RATE_LIMIT_MAX_REQUESTS = int_config("OPENKB_AI_RATE_LIMIT_MAX_REQUESTS", 5, minimum=1, maximum=100)
OPENKB_AI_RATE_LIMIT_WINDOW_SECONDS = int_config("OPENKB_AI_RATE_LIMIT_WINDOW_SECONDS", 60, minimum=10, maximum=3600)
OPENKB_AI_RATE_LIMIT_BLOCK_SECONDS = int_config("OPENKB_AI_RATE_LIMIT_BLOCK_SECONDS", 1800, minimum=60, maximum=86400)
OPENKB_AI_TIMEOUT_SECONDS = int_config("OPENKB_AI_TIMEOUT_SECONDS", 90, minimum=10, maximum=300)
OPENKB_AI_CONCURRENCY_LIMIT = int_config("OPENKB_AI_CONCURRENCY_LIMIT", 2, minimum=1, maximum=20)
# This Redis slot protects both on-disk OpenKB synchronisation and the provider
# query. Keep it safely beyond the worker hard time limit so a long-running task
# cannot briefly overlap another query after its slot expires.
OPENKB_AI_CONCURRENCY_LOCK_SECONDS = max(
    int_config("OPENKB_AI_CONCURRENCY_LOCK_SECONDS", OPENKB_AI_TIMEOUT_SECONDS + 90, minimum=30, maximum=600),
    OPENKB_AI_TIMEOUT_SECONDS + 90,
)
# Short-lived background job settings. Prompt/result text is encrypted in the
# Redis-backed cache and expires automatically; nothing is written to the DB.
OPENKB_AI_JOB_TTL_SECONDS = int_config("OPENKB_AI_JOB_TTL_SECONDS", 1800, minimum=300, maximum=86400)
OPENKB_AI_JOB_BUSY_RETRIES = int_config("OPENKB_AI_JOB_BUSY_RETRIES", 12, minimum=0, maximum=100)
OPENKB_AI_POLL_INTERVAL_MILLISECONDS = int_config("OPENKB_AI_POLL_INTERVAL_MILLISECONDS", 2000, minimum=500, maximum=10000)
OPENKB_AI_CELERY_QUEUE = config_value("OPENKB_AI_CELERY_QUEUE", "openkb_ai").strip() or "openkb_ai"

# Progressive lockout for password/MFA failures.
# Primary production policy is editable in Django Admin > Site settings.
# AUTH_LOCKOUT_POLICY_STAGES is only the early-startup/env fallback. Format:
# failure_limit:block_seconds:repeat_count
# Example below means:
# 10 failures -> 5 min block twice; 5 failures -> 15 min block twice;
# 3 failures -> 1 hour block forever.
# Failed-attempt counters reset after successful login/MFA, admin reset,
# or AUTH_LOCKOUT_STRIKE_TTL_SECONDS expiry.
AUTH_LOCKOUT_POLICY_STAGES = config_value(
    "AUTH_LOCKOUT_POLICY_STAGES",
    "10:300:2,5:900:2,3:3600:0",
)
AUTH_LOCKOUT_STRIKE_TTL_SECONDS = int_config("AUTH_LOCKOUT_STRIKE_TTL_SECONDS", 604800, minimum=3600, maximum=604800)


# ---------------------------------------------------------------------
# Django security / basics
# ---------------------------------------------------------------------

DEBUG = config_value("DJANGO_DEBUG", "false").lower() == "true"

# Django secret key must come from env/file/Vault. Do not keep an insecure
# fallback in source code because it can accidentally be used in deployment.
# In this project, DJANGO_SECRET_KEY should be stored in Vault via
# vault/bootstrap/djopenkb.env during first-time Vault seeding.
SECRET_KEY = secret_value("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY is not configured. Set it in Vault, an environment "
        "variable, or DJANGO_SECRET_KEY_FILE before starting Django."
    )

def _csv_config(name: str, default: str = "") -> list[str]:
    """Read a comma-separated config value and return trimmed non-empty items."""
    return [item.strip() for item in config_value(name, default).split(",") if item.strip()]


# Development can use localhost by default. Production must explicitly set
# the browser-facing public IP address or DNS name through .env; internal Docker names
# are intentionally not accepted public Host headers.
ALLOWED_HOSTS = _csv_config(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1" if DEBUG else "",
)
CSRF_TRUSTED_ORIGINS = _csv_config(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "https://localhost:8080,https://127.0.0.1:8080" if DEBUG else "",
)

if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "DJANGO_ALLOWED_HOSTS is required when DJANGO_DEBUG=false. "
        "Set it to the browser-facing public IP or final DNS hostname in .env."
    )
if not DEBUG and not CSRF_TRUSTED_ORIGINS:
    raise ImproperlyConfigured(
        "DJANGO_CSRF_TRUSTED_ORIGINS is required when DJANGO_DEBUG=false. "
        "Set it to the exact HTTPS browser origin in .env."
    )

# Nginx terminates HTTPS and forwards requests to Django over the internal
# Docker network. This tells Django to trust Nginx's HTTPS forwarding header.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Safe global fallback for normal and pre-MFA session cookies. The Site setting
# below remains the authoritative per-site lifetime after migrations are ready.
SESSION_COOKIE_AGE = int_config("DJANGO_SESSION_TIMEOUT_HOURS", 8, minimum=1, maximum=168) * 60 * 60
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Browser/session security hardening.
#
# Keep these strict settings active only when DEBUG=false so local development
# remains easy, while deployment gets secure cookies, HTTPS enforcement, HSTS,
# anti-clickjacking, content-type sniffing protection, and safer referrers.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = int(config_value("DJANGO_SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    LANGUAGE_COOKIE_SECURE = True

    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True

    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"

# Deny framing by default to reduce clickjacking risk.
X_FRAME_OPTIONS = "DENY"


# ---------------------------------------------------------------------
# Application definition
# ---------------------------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "kb.apps.KbConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "kb.middleware.ContentSecurityPolicyMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "kb.middleware.DisabledUserLogoutMiddleware",
    "kb.middleware.SessionTimeoutMiddleware",
    "kb.middleware.UserProfileLanguageMiddleware",
    "kb.middleware.LocalMFARequiredMiddleware",
    "kb.middleware.ForceLoginAndAdminGuardMiddleware",
    "kb.admin_security.AdminMFASessionMiddleware",
    "kb.middleware.AdminActivityLogMiddleware",
    "kb.middleware.AuthSessionCacheControlMiddleware",
    "kb.middleware.NoIndexRobotsHeaderMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "djopenkb.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "website" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.i18n",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "kb.context_processors.csp_nonce",
                "kb.context_processors.safe_back",
                "kb.context_processors.openkb_ai_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "djopenkb.wsgi.application"


# ---------------------------------------------------------------------
# Cache / logging
# ---------------------------------------------------------------------

# Shared cache used for AI rate limiting, AI concurrency locks, and auth/MFA
# progressive lockout. Production should use Redis so all Gunicorn workers share
# the same counters. Local memory is allowed only for development or an explicit
# emergency fallback.
REDIS_URL = config_value("REDIS_URL", "").strip()
DJANGO_ALLOW_LOCAL_CACHE_FALLBACK = config_value("DJANGO_ALLOW_LOCAL_CACHE_FALLBACK", "false").lower() == "true"

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "TIMEOUT": 300,
        }
    }
elif DEBUG or DJANGO_ALLOW_LOCAL_CACHE_FALLBACK:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "djopenkb-local-cache",
        }
    }
else:
    raise ImproperlyConfigured(
        "REDIS_URL is required when DJANGO_DEBUG=false. "
        "Set REDIS_URL=redis://redis:6379/1, or set "
        "DJANGO_ALLOW_LOCAL_CACHE_FALLBACK=true only as a temporary emergency fallback."
    )

# ---------------------------------------------------------------------
# Background OpenKB AI jobs (Celery + dedicated Redis broker database)
# ---------------------------------------------------------------------
# The browser receives an opaque job ID immediately, while a separate Celery
# worker invokes OpenKB. Keep the broker isolated from Django's cache DB when
# possible; Docker Compose defaults this to Redis DB 2.
OPENKB_AI_CELERY_BROKER_URL = config_value("OPENKB_AI_CELERY_BROKER_URL", REDIS_URL).strip()
if not OPENKB_AI_CELERY_BROKER_URL and not (DEBUG or DJANGO_ALLOW_LOCAL_CACHE_FALLBACK):
    raise ImproperlyConfigured("OPENKB_AI_CELERY_BROKER_URL is required for production background OpenKB AI jobs.")

CELERY_BROKER_URL = OPENKB_AI_CELERY_BROKER_URL
CELERY_TASK_DEFAULT_QUEUE = OPENKB_AI_CELERY_QUEUE
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_IGNORE_RESULT = True
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_ENABLE_REMOTE_CONTROL = False
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "visibility_timeout": max(3600, OPENKB_AI_JOB_TTL_SECONDS + OPENKB_AI_TIMEOUT_SECONDS + 60),
}
CELERY_TASK_SOFT_TIME_LIMIT = max(90, OPENKB_AI_TIMEOUT_SECONDS + 30)
CELERY_TASK_TIME_LIMIT = max(120, OPENKB_AI_TIMEOUT_SECONDS + 60)


# ---------------------------------------------------------------------
# SMTP relay article-review notifications
# ---------------------------------------------------------------------
# Notifications are intentionally disabled until the relay has been configured.
# SMTP credentials are read with secret_value(), so they belong in Vault rather
# than .env. The web service sends one Bcc notification after a submission commits.
EMAIL_NOTIFICATIONS_ENABLED = config_value("EMAIL_NOTIFICATIONS_ENABLED", "false").lower() == "true"

SMTP_RELAY_HOST = config_value("SMTP_RELAY_HOST", "").strip()
SMTP_RELAY_PORT = int_config("SMTP_RELAY_PORT", 587, minimum=1, maximum=65535)
SMTP_RELAY_USE_TLS = config_value("SMTP_RELAY_USE_TLS", "true").lower() == "true"
SMTP_RELAY_USE_SSL = config_value("SMTP_RELAY_USE_SSL", "false").lower() == "true"
SMTP_RELAY_TIMEOUT_SECONDS = int_config("SMTP_RELAY_TIMEOUT_SECONDS", 10, minimum=1, maximum=120)
SMTP_RELAY_CA_CERT_FILE = config_value("SMTP_RELAY_CA_CERT_FILE", "").strip()
SMTP_RELAY_USERNAME = secret_value("SMTP_RELAY_USERNAME", "").strip()
SMTP_RELAY_PASSWORD = secret_value("SMTP_RELAY_PASSWORD", "")
SMTP_FROM_EMAIL = config_value("SMTP_FROM_EMAIL", "").strip()
SMTP_RELAY_ALLOWED_RECIPIENT_DOMAINS = tuple(
    dict.fromkeys(
        domain.strip().casefold()
        for domain in config_value("SMTP_RELAY_ALLOWED_RECIPIENT_DOMAINS", "").split(",")
        if domain.strip()
    )
)
SITE_BASE_URL = config_value("SITE_BASE_URL", "").strip().rstrip("/")
EMAIL_SUBJECT_PREFIX = config_value("EMAIL_SUBJECT_PREFIX", "[Knowledge Repository]").strip()
if EMAIL_SUBJECT_PREFIX:
    EMAIL_SUBJECT_PREFIX = f"{EMAIL_SUBJECT_PREFIX} "

# Django's SMTP backend performs the authentication after STARTTLS/implicit TLS.
# The custom backend adds support for an internally issued relay certificate
# through SMTP_RELAY_CA_CERT_FILE while retaining strict certificate validation.
EMAIL_BACKEND = "kb.email_backend.ADRelayEmailBackend"
EMAIL_HOST = SMTP_RELAY_HOST
EMAIL_PORT = SMTP_RELAY_PORT
EMAIL_HOST_USER = SMTP_RELAY_USERNAME
EMAIL_HOST_PASSWORD = SMTP_RELAY_PASSWORD
EMAIL_USE_TLS = SMTP_RELAY_USE_TLS
EMAIL_USE_SSL = SMTP_RELAY_USE_SSL
EMAIL_TIMEOUT = SMTP_RELAY_TIMEOUT_SECONDS
DEFAULT_FROM_EMAIL = SMTP_FROM_EMAIL or "noreply@localhost"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

if SMTP_RELAY_USE_TLS and SMTP_RELAY_USE_SSL:
    raise ImproperlyConfigured(
        "Configure exactly one SMTP transport: SMTP_RELAY_USE_TLS=true for STARTTLS "
        "or SMTP_RELAY_USE_SSL=true for implicit TLS, not both."
    )

if EMAIL_NOTIFICATIONS_ENABLED:
    missing_smtp_values = [
        name
        for name, value in {
            "SMTP_RELAY_HOST": SMTP_RELAY_HOST,
            "SMTP_RELAY_USERNAME": SMTP_RELAY_USERNAME,
            "SMTP_RELAY_PASSWORD": SMTP_RELAY_PASSWORD,
            "SMTP_FROM_EMAIL": SMTP_FROM_EMAIL,
            "SMTP_RELAY_ALLOWED_RECIPIENT_DOMAINS": ",".join(SMTP_RELAY_ALLOWED_RECIPIENT_DOMAINS),
            "SITE_BASE_URL": SITE_BASE_URL,
        }.items()
        if not value
    ]
    if missing_smtp_values:
        raise ImproperlyConfigured(
            "EMAIL_NOTIFICATIONS_ENABLED=true requires: " + ", ".join(missing_smtp_values)
        )

    if not (SMTP_RELAY_USE_TLS or SMTP_RELAY_USE_SSL):
        raise ImproperlyConfigured(
            "EMAIL_NOTIFICATIONS_ENABLED=true requires TLS. Set SMTP_RELAY_USE_TLS=true "
            "for STARTTLS or SMTP_RELAY_USE_SSL=true for implicit TLS."
        )

    parsed_site_url = urlparse(SITE_BASE_URL)
    if parsed_site_url.scheme != "https" or not parsed_site_url.netloc or parsed_site_url.query or parsed_site_url.fragment:
        raise ImproperlyConfigured(
            "SITE_BASE_URL must be the exact HTTPS browser origin, for example "
            "https://<PUBLIC_HOSTNAME> or https://<INTERNAL_SERVER_IP>:8080."
        )

    if SMTP_RELAY_CA_CERT_FILE and not Path(SMTP_RELAY_CA_CERT_FILE).is_file():
        raise ImproperlyConfigured(
            "SMTP_RELAY_CA_CERT_FILE is configured but the file is not available "
            "inside the container."
        )


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "kb": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_KB_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "kb.backends": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LDAP_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "django_auth_ldap": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LDAP_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}


# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------

# PostgreSQL is the default database for this project.
# Docker Compose provides these POSTGRES_* values to the web container.
# For quick local testing outside Docker, set USE_SQLITE=true to temporarily use db.sqlite3.
USE_SQLITE = os.getenv("USE_SQLITE", "false").lower() == "true"

if USE_SQLITE:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    POSTGRES_PASSWORD = secret_value("POSTGRES_PASSWORD", "djopenkb_password" if DEBUG else "")
    if not POSTGRES_PASSWORD:
        raise ImproperlyConfigured(
            "POSTGRES_PASSWORD is required when USE_SQLITE=false and DJANGO_DEBUG=false. "
            "Store POSTGRES_PASSWORD in Vault, an environment variable, or POSTGRES_PASSWORD_FILE."
        )

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "djopenkb"),
            "USER": os.getenv("POSTGRES_USER", "djopenkb"),
            "PASSWORD": POSTGRES_PASSWORD,
            "HOST": os.getenv("POSTGRES_HOST", "db"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
        }
    }


# ---------------------------------------------------------------------
# Authentication / LDAP / Active Directory
# ---------------------------------------------------------------------

LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "/home/"
LOGOUT_REDIRECT_URL = "/"

# Site-level TOTP MFA. Enforced as a login criterion for local and LDAP/AD users.
MFA_TOTP_ISSUER = config_value("MFA_TOTP_ISSUER", "Knowledge Repository")
# Number of adjacent 30-second TOTP windows accepted before/after the
# current one. 2 tolerates small server/phone clock drift without making MFA
# too loose. Keep this low and fix NTP if clocks drift by more than a minute.
try:
    MFA_TOTP_VALID_WINDOW = max(0, min(int(config_value("MFA_TOTP_VALID_WINDOW", "2")), 3))
except (TypeError, ValueError):
    MFA_TOTP_VALID_WINDOW = 2

# Application-level encryption key for recoverable sensitive database fields,
# such as TOTP authenticator secrets. Prefer storing this in Vault as
# DJANGO_FIELD_ENCRYPTION_KEY. If unset, Django falls back to DJANGO_SECRET_KEY
# so existing deployments still start. Do not rotate this after users have MFA
# devices unless you first re-encrypt the stored values.
FIELD_ENCRYPTION_KEY = secret_value("DJANGO_FIELD_ENCRYPTION_KEY", SECRET_KEY)

LDAP_ENABLED = config_value("LDAP_ENABLED", "false").lower() == "true"
# Placeholder LDAP exists only for local development while an AD server is unavailable.
# It must never silently fall back to a known shared password.
LDAP_PLACEHOLDER_ENABLED = config_value("LDAP_PLACEHOLDER_ENABLED", "false").lower() == "true"
LDAP_PLACEHOLDER_AUTO_CREATE_USERS = config_value("LDAP_PLACEHOLDER_AUTO_CREATE_USERS", "false").lower() == "true"
LDAP_PLACEHOLDER_PASSWORD = secret_value("LDAP_PLACEHOLDER_PASSWORD", "").strip()

if LDAP_PLACEHOLDER_ENABLED:
    if not DEBUG:
        raise ImproperlyConfigured(
            "LDAP_PLACEHOLDER_ENABLED may only be enabled when DJANGO_DEBUG=true. "
            "Use real LDAP/AD authentication for deployed environments."
        )
    if not LDAP_PLACEHOLDER_PASSWORD:
        raise ImproperlyConfigured(
            "LDAP_PLACEHOLDER_ENABLED=true requires a non-empty LDAP_PLACEHOLDER_PASSWORD."
        )
    if LDAP_PLACEHOLDER_AUTO_CREATE_USERS and not DEBUG:
        raise ImproperlyConfigured(
            "LDAP_PLACEHOLDER_AUTO_CREATE_USERS may only be enabled when DJANGO_DEBUG=true."
        )
elif LDAP_PLACEHOLDER_AUTO_CREATE_USERS:
    raise ImproperlyConfigured(
        "LDAP_PLACEHOLDER_AUTO_CREATE_USERS=true requires LDAP_PLACEHOLDER_ENABLED=true."
    )

# These are used by kb.backends.NextLabsLDAPBackend to normalize AD usernames.
# Example lab values:
#   LDAP_AD_DOMAIN=openkb.local
#   LDAP_NETBIOS_DOMAIN=OPENKB
LDAP_AD_DOMAIN = config_value("LDAP_AD_DOMAIN", "").strip().lower()
LDAP_NETBIOS_DOMAIN = config_value("LDAP_NETBIOS_DOMAIN", "").strip().upper()
LDAP_ALLOWED_EMAIL_DOMAINS = [
    item.strip().lower()
    for item in config_value("LDAP_ALLOWED_EMAIL_DOMAINS", "").split(",")
    if item.strip()
]

if LDAP_ENABLED:
    try:
        import ldap
        from django_auth_ldap.config import LDAPSearch
    except ImportError as exc:
        raise ImportError(
            "LDAP_ENABLED=true but LDAP packages are missing. "
            "Make sure Dockerfile installs libldap2-dev, libsasl2-dev, ldap-utils, "
            "and pip installs django-auth-ldap."
        ) from exc

    AUTHENTICATION_BACKENDS = [
        "kb.backends.NextLabsLDAPBackend",
        "kb.backends.PlaceholderLDAPBackend",
        "kb.backends.EmailOrUsernameModelBackend",
    ]

    AUTH_LDAP_SERVER_URI = config_value("LDAP_SERVER_URI", "").strip()
    if not AUTH_LDAP_SERVER_URI:
        raise ImproperlyConfigured(
            "LDAP_ENABLED=true but LDAP_SERVER_URI is not configured. "
            "Set LDAP_SERVER_URI in .env, or store LDAP_SERVER_URI in Vault. "
            "Example: ldaps://dc01.openkb.local:636"
        )

    LDAP_START_TLS = config_value("LDAP_START_TLS", "false").lower() == "true"
    LDAP_ALLOW_INSECURE = config_value("LDAP_ALLOW_INSECURE", "false").lower() == "true"

    # Production safety guard: require encrypted LDAP unless explicitly waived.
    # Preferred AD setup is LDAPS on 636 with a Domain Controller certificate.
    if (
        not DEBUG
        and not LDAP_ALLOW_INSECURE
        and AUTH_LDAP_SERVER_URI.lower().startswith("ldap://")
        and not LDAP_START_TLS
    ):
        raise ImproperlyConfigured(
            "LDAP_ENABLED=true with DJANGO_DEBUG=false must use encrypted LDAP. "
            "Set LDAP_SERVER_URI=ldaps://<dc-hostname>:636, or enable LDAP_START_TLS=true, "
            "or explicitly set LDAP_ALLOW_INSECURE=true only for a temporary lab exception."
        )

    # Optional StartTLS support for ldap:// servers. For Active Directory LDAPS,
    # prefer LDAP_SERVER_URI=ldaps://dc01.openkb.local:636 and LDAP_START_TLS=false.
    AUTH_LDAP_START_TLS = LDAP_START_TLS

    LDAP_CA_CERT_FILE = config_value("LDAP_CA_CERT_FILE", "").strip()
    LDAP_TLS_REQUIRE_CERT = config_value("LDAP_TLS_REQUIRE_CERT", "demand").strip().lower()
    LDAP_TLS_REQUIRE_CERT_MAP = {
        "never": ldap.OPT_X_TLS_NEVER,
        "allow": ldap.OPT_X_TLS_ALLOW,
        "try": ldap.OPT_X_TLS_TRY,
        "demand": ldap.OPT_X_TLS_DEMAND,
        "hard": ldap.OPT_X_TLS_HARD,
    }
    if LDAP_TLS_REQUIRE_CERT not in LDAP_TLS_REQUIRE_CERT_MAP:
        raise ImproperlyConfigured(
            "LDAP_TLS_REQUIRE_CERT must be one of: never, allow, try, demand, hard."
        )

    # Configure python-ldap TLS globally before django-auth-ldap opens connections.
    # The Django container should only mount the issuing CA certificate, not the
    # Domain Controller private key.
    if LDAP_CA_CERT_FILE:
        ldap.set_option(ldap.OPT_X_TLS_CACERTFILE, LDAP_CA_CERT_FILE)
    ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, LDAP_TLS_REQUIRE_CERT_MAP[LDAP_TLS_REQUIRE_CERT])

    # Some python-ldap/OpenLDAP builds raise ValueError for OPT_X_TLS_NEWCTX
    # during Django settings import. This option is only a TLS context refresh;
    # failing it should not prevent the web container from starting.
    try:
        ldap.set_option(ldap.OPT_X_TLS_NEWCTX, 0)
    except (AttributeError, ValueError, ldap.LDAPError):
        pass

    # Use a low-privilege AD service account for searching users.
    # Example:
    #   CN=svc_djopenkb,OU=Service Accounts,DC=openkb,DC=local
    AUTH_LDAP_BIND_DN = config_value("LDAP_BIND_DN", "")
    AUTH_LDAP_BIND_PASSWORD = secret_value("LDAP_BIND_PASSWORD", "")

    LDAP_USER_SEARCH_BASE = config_value("LDAP_USER_SEARCH_BASE", "").strip()
    if not LDAP_USER_SEARCH_BASE:
        raise ImproperlyConfigured(
            "LDAP_ENABLED=true but LDAP_USER_SEARCH_BASE is not configured. "
            "Set it in .env, for example: DC=company,DC=local"
        )

    AUTH_LDAP_USER_SEARCH = LDAPSearch(
        LDAP_USER_SEARCH_BASE,
        ldap.SCOPE_SUBTREE,
        config_value(
            "LDAP_USER_FILTER",
            "(|(userPrincipalName=%(user)s)(sAMAccountName=%(user)s)(mail=%(user)s))",
        ),
    )

    AUTH_LDAP_USER_ATTR_MAP = {
        "first_name": "givenName",
        "last_name": "sn",
        "email": "mail",
    }

    # All valid AD users found by AUTH_LDAP_USER_SEARCH may authenticate.
    # The LDAP bind account remains a low-privilege, read-only search account;
    # it is not used to grant or modify permissions in Active Directory.

    AUTH_LDAP_ALWAYS_UPDATE_USER = True
    AUTH_LDAP_CREATE_USERS = True

    AUTH_LDAP_CONNECTION_OPTIONS = {
        ldap.OPT_REFERRALS: 0,
        ldap.OPT_NETWORK_TIMEOUT: int(config_value("LDAP_NETWORK_TIMEOUT", "5")),
        ldap.OPT_TIMEOUT: int(config_value("LDAP_OPERATION_TIMEOUT", "5")),
        ldap.OPT_X_TLS_REQUIRE_CERT: LDAP_TLS_REQUIRE_CERT_MAP[LDAP_TLS_REQUIRE_CERT],
    }
    if LDAP_CA_CERT_FILE:
        AUTH_LDAP_CONNECTION_OPTIONS[ldap.OPT_X_TLS_CACERTFILE] = LDAP_CA_CERT_FILE

    AUTH_LDAP_CACHE_TIMEOUT = int(config_value("LDAP_CACHE_TIMEOUT", "3600"))

else:
    AUTHENTICATION_BACKENDS = [
        "kb.backends.PlaceholderLDAPBackend",
        "kb.backends.EmailOrUsernameModelBackend",
    ]


# ---------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ---------------------------------------------------------------------
# Internationalization
# ---------------------------------------------------------------------

LANGUAGE_CODE = "en"

LANGUAGES = [
    ("en", "English"),
    ("de", "Deutsch"),
    ("da", "Dansk"),
    ("es", "Español"),
    ("zh-hans", "简体中文"),
    ("ru", "Русский"),
    ("pt-br", "Português do Brasil"),
    ("ja", "日本語"),
    ("fi", "Suomi"),
    ("sv", "Svenska"),
    ("tr", "Türkçe"),
    ("fa", "فارسی"),
    ("ms", "Bahasa Melayu"),
    ("ta", "தமிழ்"),
    ("fr", "Français"),
    ("it", "Italiano"),
    ("ko", "한국어"),
    ("id", "Bahasa Indonesia"),
    ("th", "ไทย"),
    ("vi", "Tiếng Việt"),
    ("nl", "Nederlands"),
    ("pl", "Polski"),
    ("ar", "العربية"),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

LANGUAGE_COOKIE_AGE = 60 * 60 * 24 * 365
LANGUAGE_COOKIE_SAMESITE = "Lax"

TIME_ZONE = "Asia/Singapore"

USE_I18N = True

USE_TZ = True


# ---------------------------------------------------------------------
# Static files
# ---------------------------------------------------------------------

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "website" / "static",
]

# ---------------------------------------------------------------------
# Default primary key field type
# ---------------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"